import StatInference.Optimization.Basic

/-!
# Gradient-span algorithms

This module starts the Chapter 4 lower-bound layer for Chewi's optimization
notes.  It records Definition 4.3 in a reusable form and proves the immediate
source example: every fixed-step gradient-descent trajectory is a gradient-span
trajectory.
-/

namespace StatInference
namespace Optimization

open Set
open scoped InnerProductSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/--
The linear span of the gradients queried through time `n`.

This is the subspace appearing in Chewi Definition 4.3:
`span {grad (x 0), ..., grad (x n)}`.
-/
def gradientSpanSubmodule (grad : E -> E) (x : ℕ -> E)
    (n : ℕ) : Submodule ℝ E :=
  Submodule.span ℝ ((fun k : ℕ => grad (x k)) '' {k : ℕ | k ≤ n})

/-- The affine space `x_0 + span {grad (x 0), ..., grad (x n)}`. -/
def affineGradientSpan (grad : E -> E) (x : ℕ -> E) (n : ℕ) : Set E :=
  {y | y - x 0 ∈ gradientSpanSubmodule grad x n}

/--
Chewi Definition 4.3, specialized to deterministic sequences generated from
an explicit gradient oracle.

The condition `x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n` is the vector
space form of `x_{n+1} ∈ x_0 + span {grad f(x_0), ..., grad f(x_n)}`.
-/
def IsGradientSpanTrajectory (grad : E -> E) (x : ℕ -> E) : Prop :=
  ∀ n, x (n + 1) ∈ affineGradientSpan grad x n

/-- Unfolding helper for the affine-gradient-span display. -/
theorem mem_affineGradientSpan_iff {grad : E -> E} {x : ℕ -> E}
    {n : ℕ} {y : E} :
    y ∈ affineGradientSpan grad x n ↔
      y - x 0 ∈ gradientSpanSubmodule grad x n :=
  Iff.rfl

/-- Each queried gradient belongs to the gradient span through its query time. -/
theorem gradient_mem_gradientSpanSubmodule (grad : E -> E) (x : ℕ -> E)
    (n : ℕ) :
    grad (x n) ∈ gradientSpanSubmodule grad x n := by
  exact Submodule.subset_span ⟨n, by simp, rfl⟩

/-- The gradient spans are monotone in the number of allowed oracle queries. -/
theorem gradientSpanSubmodule_mono (grad : E -> E) (x : ℕ -> E)
    {m n : ℕ} (hmn : m ≤ n) :
    gradientSpanSubmodule grad x m ≤ gradientSpanSubmodule grad x n := by
  refine Submodule.span_mono ?_
  rintro v ⟨k, hk, rfl⟩
  exact ⟨k, hk.trans hmn, rfl⟩

/--
One gradient-descent step preserves membership in the affine space generated by
the gradients seen so far.
-/
theorem gradientDescentStep_sub_initial_mem_gradientSpanSubmodule
    (grad : E -> E) (x : ℕ -> E) (h : ℝ) (n : ℕ)
    (hprev : x n - x 0 ∈ gradientSpanSubmodule grad x n) :
    gradientDescentStep grad h (x n) - x 0 ∈
      gradientSpanSubmodule grad x n := by
  have hgrad :
      grad (x n) ∈ gradientSpanSubmodule grad x n :=
    gradient_mem_gradientSpanSubmodule grad x n
  have hstep :
      (x n - x 0) - h • grad (x n) ∈
        gradientSpanSubmodule grad x n :=
    Submodule.sub_mem _ hprev (Submodule.smul_mem _ h hgrad)
  simpa [gradientDescentStep, sub_eq_add_neg, add_assoc, add_left_comm,
    add_comm] using hstep

/-- The source example after Definition 4.3: fixed-step GD is gradient-span. -/
theorem IsGradientDescentTrajectory.isGradientSpanTrajectory
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) :
    IsGradientSpanTrajectory grad x := by
  intro n
  change x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n
  induction n with
  | zero =>
      have hgrad :
          grad (x 0) ∈ gradientSpanSubmodule grad x 0 :=
        gradient_mem_gradientSpanSubmodule grad x 0
      have hmem :
          (-h) • grad (x 0) ∈ gradientSpanSubmodule grad x 0 :=
        Submodule.smul_mem _ (-h) hgrad
      simpa [hx 0, gradientDescentStep, sub_eq_add_neg, neg_smul, add_assoc,
        add_left_comm, add_comm] using hmem
  | succ n ih =>
      have hprev :
          x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x (n + 1) :=
        gradientSpanSubmodule_mono grad x (Nat.le_succ n) ih
      have hstep :
          gradientDescentStep grad h (x (n + 1)) - x 0 ∈
            gradientSpanSubmodule grad x (n + 1) :=
        gradientDescentStep_sub_initial_mem_gradientSpanSubmodule
          grad x h (n + 1) hprev
      simpa [Nat.succ_eq_add_one, add_assoc, hx (n + 1)] using hstep

/--
Convenience wrapper for the textbook display:
`x_{n+1} - x_0` lies in the span of gradients through time `n` for GD.
-/
theorem gradientDescentTrajectory_mem_gradientSpanSubmodule
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) (n : ℕ) :
    x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n :=
  hx.isGradientSpanTrajectory n

/--
Source-shaped affine version of the GD example:
`x_{n+1} ∈ x_0 + span {grad (x_0), ..., grad (x_n)}`.
-/
theorem gradientDescentTrajectory_mem_affineGradientSpan
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) (n : ℕ) :
    x (n + 1) ∈ affineGradientSpan grad x n :=
  hx.isGradientSpanTrajectory n

end Optimization
end StatInference
