import StatInference.Optimization.Basic

/-!
# Gradient-span algorithms

This module starts the Chapter 4 lower-bound layer for Chewi's optimization
notes.  It records Definition 4.3 in a reusable form and proves the immediate
source example: every fixed-step gradient-descent trajectory is a gradient-span
trajectory.
-/

namespace StatInference
namespace Optimization

open Set
open scoped InnerProductSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/--
The linear span of the gradients queried through time `n`.

This is the subspace appearing in Chewi Definition 4.3:
`span {grad (x 0), ..., grad (x n)}`.
-/
def gradientSpanSubmodule (grad : E -> E) (x : ℕ -> E)
    (n : ℕ) : Submodule ℝ E :=
  Submodule.span ℝ ((fun k : ℕ => grad (x k)) '' {k : ℕ | k ≤ n})

/-- The affine space `x_0 + span {grad (x 0), ..., grad (x n)}`. -/
def affineGradientSpan (grad : E -> E) (x : ℕ -> E) (n : ℕ) : Set E :=
  {y | y - x 0 ∈ gradientSpanSubmodule grad x n}

/--
Chewi Definition 4.3, specialized to deterministic sequences generated from
an explicit gradient oracle.

The condition `x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n` is the vector
space form of `x_{n+1} ∈ x_0 + span {grad f(x_0), ..., grad f(x_n)}`.
-/
def IsGradientSpanTrajectory (grad : E -> E) (x : ℕ -> E) : Prop :=
  ∀ n, x (n + 1) ∈ affineGradientSpan grad x n

/-- Unfolding helper for the affine-gradient-span display. -/
theorem mem_affineGradientSpan_iff {grad : E -> E} {x : ℕ -> E}
    {n : ℕ} {y : E} :
    y ∈ affineGradientSpan grad x n ↔
      y - x 0 ∈ gradientSpanSubmodule grad x n :=
  Iff.rfl

/-- Each queried gradient belongs to the gradient span through its query time. -/
theorem gradient_mem_gradientSpanSubmodule (grad : E -> E) (x : ℕ -> E)
    (n : ℕ) :
    grad (x n) ∈ gradientSpanSubmodule grad x n := by
  exact Submodule.subset_span ⟨n, by simp, rfl⟩

/-- The gradient spans are monotone in the number of allowed oracle queries. -/
theorem gradientSpanSubmodule_mono (grad : E -> E) (x : ℕ -> E)
    {m n : ℕ} (hmn : m ≤ n) :
    gradientSpanSubmodule grad x m ≤ gradientSpanSubmodule grad x n := by
  refine Submodule.span_mono ?_
  rintro v ⟨k, hk, rfl⟩
  exact ⟨k, hk.trans hmn, rfl⟩

/--
One gradient-descent step preserves membership in the affine space generated by
the gradients seen so far.
-/
theorem gradientDescentStep_sub_initial_mem_gradientSpanSubmodule
    (grad : E -> E) (x : ℕ -> E) (h : ℝ) (n : ℕ)
    (hprev : x n - x 0 ∈ gradientSpanSubmodule grad x n) :
    gradientDescentStep grad h (x n) - x 0 ∈
      gradientSpanSubmodule grad x n := by
  have hgrad :
      grad (x n) ∈ gradientSpanSubmodule grad x n :=
    gradient_mem_gradientSpanSubmodule grad x n
  have hstep :
      (x n - x 0) - h • grad (x n) ∈
        gradientSpanSubmodule grad x n :=
    Submodule.sub_mem _ hprev (Submodule.smul_mem _ h hgrad)
  simpa [gradientDescentStep, sub_eq_add_neg, add_assoc, add_left_comm,
    add_comm] using hstep

/-- The source example after Definition 4.3: fixed-step GD is gradient-span. -/
theorem IsGradientDescentTrajectory.isGradientSpanTrajectory
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) :
    IsGradientSpanTrajectory grad x := by
  intro n
  change x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n
  induction n with
  | zero =>
      have hgrad :
          grad (x 0) ∈ gradientSpanSubmodule grad x 0 :=
        gradient_mem_gradientSpanSubmodule grad x 0
      have hmem :
          (-h) • grad (x 0) ∈ gradientSpanSubmodule grad x 0 :=
        Submodule.smul_mem _ (-h) hgrad
      simpa [hx 0, gradientDescentStep, sub_eq_add_neg, neg_smul, add_assoc,
        add_left_comm, add_comm] using hmem
  | succ n ih =>
      have hprev :
          x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x (n + 1) :=
        gradientSpanSubmodule_mono grad x (Nat.le_succ n) ih
      have hstep :
          gradientDescentStep grad h (x (n + 1)) - x 0 ∈
            gradientSpanSubmodule grad x (n + 1) :=
        gradientDescentStep_sub_initial_mem_gradientSpanSubmodule
          grad x h (n + 1) hprev
      simpa [Nat.succ_eq_add_one, add_assoc, hx (n + 1)] using hstep

/--
Convenience wrapper for the textbook display:
`x_{n+1} - x_0` lies in the span of gradients through time `n` for GD.
-/
theorem gradientDescentTrajectory_mem_gradientSpanSubmodule
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) (n : ℕ) :
    x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n :=
  hx.isGradientSpanTrajectory n

/--
Source-shaped affine version of the GD example:
`x_{n+1} ∈ x_0 + span {grad (x_0), ..., grad (x_n)}`.
-/
theorem gradientDescentTrajectory_mem_affineGradientSpan
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) (n : ℕ) :
    x (n + 1) ∈ affineGradientSpan grad x n :=
  hx.isGradientSpanTrajectory n

section CoordinatePrefix

/--
The coordinate prefix subspace used in Chewi's proof of Theorem 4.4.

In zero-based `Fin d` coordinates, this is the source subspace
`V_n = {x : x[k] = 0 for k = n + 1, ..., d}`: the coordinates with
`n <= i.val` vanish.
-/
def coordinatePrefixSubmodule (d n : ℕ) :
    Submodule ℝ (EuclideanSpace ℝ (Fin d)) where
  carrier := {x | ∀ i : Fin d, n ≤ i.1 -> x i = 0}
  zero_mem' := by
    intro i hi
    rfl
  add_mem' := by
    intro x y hx hy i hi
    simp [hx i hi, hy i hi]
  smul_mem' := by
    intro a x hx i hi
    simp [hx i hi]

/-- Membership in the coordinate-prefix subspace is just coordinate vanishing. -/
theorem mem_coordinatePrefixSubmodule_iff {d n : ℕ}
    {x : EuclideanSpace ℝ (Fin d)} :
    x ∈ coordinatePrefixSubmodule d n ↔
      ∀ i : Fin d, n ≤ i.1 -> x i = 0 :=
  Iff.rfl

/-- The source subspaces `V_n` are monotone in `n`. -/
theorem coordinatePrefixSubmodule_mono (d : ℕ) {m n : ℕ} (hmn : m ≤ n) :
    coordinatePrefixSubmodule d m ≤ coordinatePrefixSubmodule d n := by
  intro x hx i hi
  exact hx i (hmn.trans hi)

/-- Once the prefix length reaches the dimension, the coordinate subspace is all space. -/
theorem coordinatePrefixSubmodule_eq_top_of_le {d n : ℕ} (hdn : d ≤ n) :
    coordinatePrefixSubmodule d n = ⊤ := by
  ext x
  constructor
  · intro hx
    exact Submodule.mem_top
  · intro hx i hi
    exact (Nat.not_lt_of_ge (hdn.trans hi) i.2).elim

/--
Extended chain node values for Chewi's lower-bound quadratic.

The boundary nodes are `z_0 = 1` and `z_{d+1} = 0`; the interior nodes are
`z_{i+1} = x_i`.  This lets the objective be written as a uniform finite
sum of squared edge differences.
-/
noncomputable def lowerBoundChainNode (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) (j : Fin (d + 2)) : ℝ :=
  if hzero : j.1 = 0 then
    1
  else if hlast : j.1 = d + 1 then
    0
  else
    x ⟨j.1 - 1, by omega⟩

/-- The `k`th edge difference `z_{k+1} - z_k` in the lower-bound chain. -/
noncomputable def lowerBoundChainEdge (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) (k : Fin (d + 1)) : ℝ :=
  lowerBoundChainNode d x ⟨k.1 + 1, by omega⟩ -
    lowerBoundChainNode d x ⟨k.1, by omega⟩

/--
Chewi's tridiagonal lower-bound quadratic, written as the squared energy of
the boundary chain `1, x_0, ..., x_{d-1}, 0`.
-/
noncomputable def lowerBoundChainObjective (beta : ℝ) (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) : ℝ :=
  (beta / 8) * ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ)

/--
Chewi's unshifted textbook lower-bound quadratic.

The edge-energy objective above is this source objective plus the harmless
constant `beta / 8`, because the first boundary edge is `(x[1] - 1)^2`.
-/
noncomputable def lowerBoundChainTextbookObjective (beta : ℝ) (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) : ℝ :=
  lowerBoundChainObjective beta d x - beta / 8

/-- Gaps are unchanged by the constant shift from the source objective. -/
theorem lowerBoundChainTextbookObjective_gap_eq_objective_gap
    (beta : ℝ) (d : ℕ) (x y : EuclideanSpace ℝ (Fin d)) :
    lowerBoundChainTextbookObjective beta d x -
        lowerBoundChainTextbookObjective beta d y =
      lowerBoundChainObjective beta d x - lowerBoundChainObjective beta d y := by
  simp [lowerBoundChainTextbookObjective]

/-- Telescoping sum for forward differences on a finite `Fin` chain. -/
theorem finSum_forwardDifference (n : ℕ) (z : Fin (n + 2) -> ℝ) :
    (∑ k : Fin (n + 1),
        (z ⟨k.1 + 1, by omega⟩ - z ⟨k.1, by omega⟩)) =
      z (Fin.last (n + 1)) - z 0 := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [Fin.sum_univ_castSucc]
      have hcast :
          (∑ k : Fin (n + 1),
              (z ⟨(Fin.castSucc k).1 + 1, by omega⟩ -
                z ⟨(Fin.castSucc k).1, by omega⟩)) =
            z ⟨n + 1, by omega⟩ - z 0 := by
        simpa [Fin.val_castSucc, Fin.val_last] using
          ih (fun j : Fin (n + 2) => z (Fin.castSucc j))
      rw [hcast]
      simp [Fin.val_last]
      congr

/-- The edge residuals telescope from boundary value `1` to boundary value `0`. -/
theorem lowerBoundChainEdge_sum (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) :
    (∑ k : Fin (d + 1), lowerBoundChainEdge d x k) = -1 := by
  have htel := finSum_forwardDifference d (fun j => lowerBoundChainNode d x j)
  simpa [lowerBoundChainEdge, lowerBoundChainNode, Fin.val_last] using htel

/--
If every queried gradient through time `n` lies in `V_{n+1}`, then the
gradient span through time `n` is contained in `V_{n+1}`.
-/
theorem gradientSpanSubmodule_le_coordinatePrefixSubmodule
    {d : ℕ}
    {grad : EuclideanSpace ℝ (Fin d) -> EuclideanSpace ℝ (Fin d)}
    {x : ℕ -> EuclideanSpace ℝ (Fin d)} {n : ℕ}
    (hgrad : ∀ ⦃k : ℕ⦄, k ≤ n ->
      grad (x k) ∈ coordinatePrefixSubmodule d (n + 1)) :
    gradientSpanSubmodule grad x n ≤ coordinatePrefixSubmodule d (n + 1) := by
  refine Submodule.span_le.mpr ?_
  rintro v ⟨k, hk, rfl⟩
  exact hgrad hk

/--
Abstract induction in Chewi Theorem 4.4: if the oracle gradients satisfy
`grad (x_k) ∈ V_{k+1}` along a gradient-span trajectory starting from zero,
then every iterate satisfies `x_n ∈ V_n`.
-/
theorem gradientSpanTrajectory_mem_coordinatePrefixSubmodule_of_grad_mem_next
    {d : ℕ}
    {grad : EuclideanSpace ℝ (Fin d) -> EuclideanSpace ℝ (Fin d)}
    {x : ℕ -> EuclideanSpace ℝ (Fin d)}
    (hx0 : x 0 = 0)
    (hspan : IsGradientSpanTrajectory grad x)
    (hgrad : ∀ k, x k ∈ coordinatePrefixSubmodule d k ->
      grad (x k) ∈ coordinatePrefixSubmodule d (k + 1)) :
    ∀ n, x n ∈ coordinatePrefixSubmodule d n := by
  intro n
  induction n using Nat.strong_induction_on with
  | h n ih =>
      cases n with
      | zero =>
          simp [hx0, coordinatePrefixSubmodule]
      | succ n =>
          have hspan_n :
              x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n :=
            mem_affineGradientSpan_iff.mp (hspan n)
          have hle :
              gradientSpanSubmodule grad x n ≤
                coordinatePrefixSubmodule d (n + 1) := by
            refine gradientSpanSubmodule_le_coordinatePrefixSubmodule ?_
            intro k hk
            have hxk : x k ∈ coordinatePrefixSubmodule d k :=
              ih k (Nat.lt_succ_of_le hk)
            exact coordinatePrefixSubmodule_mono d (Nat.succ_le_succ hk)
              (hgrad k hxk)
          have hx_sub :
              x (n + 1) - x 0 ∈ coordinatePrefixSubmodule d (n + 1) :=
            hle hspan_n
          simpa [hx0] using hx_sub

/--
The gradient of Chewi's tridiagonal lower-bound quadratic, up to the harmless
global scaling factor `beta / 4`.

In zero-based coordinates this is the finite-difference chain
`2*x[i] - x[i-1] - x[i+1]`, with the source forcing term `-e_1` represented
by the `i = 0` boundary value `1`.
-/
noncomputable def lowerBoundChainGradient (beta : ℝ) (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) : EuclideanSpace ℝ (Fin d) :=
  WithLp.toLp 2 fun i : Fin d =>
    (beta / 4) *
      (2 * x i -
        (if _ : 0 < i.1 then
          x ⟨i.1 - 1, lt_of_le_of_lt (Nat.sub_le i.1 1) i.2⟩
        else
          1) -
        (if hnext : i.1 + 1 < d then
          x ⟨i.1 + 1, hnext⟩
        else
          0))

/--
The tridiagonal gradient is the difference of adjacent edge residuals of the
chain objective.  This is the algebraic core of the objective-gradient bridge.
-/
theorem lowerBoundChainGradient_eq_edgeDifference
    (beta : ℝ) (d : ℕ) (x : EuclideanSpace ℝ (Fin d)) :
    lowerBoundChainGradient beta d x =
      WithLp.toLp 2 fun i : Fin d =>
        (beta / 4) *
          (lowerBoundChainEdge d x ⟨i.1, by omega⟩ -
            lowerBoundChainEdge d x ⟨i.1 + 1, by omega⟩) := by
  ext i
  by_cases hprev : 0 < i.1
  · by_cases hnext : i.1 + 1 < d
    · have hi_ne_zero : i.1 ≠ 0 := by omega
      have hi_ne_d : i.1 ≠ d := by omega
      have hi_ne_succd : i.1 ≠ d + 1 := by omega
      have hnext_node_not_last : 1 + (i.1 + 1) ≠ d + 1 := by omega
      simp [lowerBoundChainGradient, lowerBoundChainEdge, lowerBoundChainNode,
        PiLp.toLp_apply, hprev, hnext, hi_ne_zero, hi_ne_d, hi_ne_succd,
        Nat.add_comm]
      left
      simp [hnext_node_not_last]
      ring_nf
    · have hi_last : i.1 + 1 = d := by omega
      have hi_ne_zero : i.1 ≠ 0 := by omega
      have hi_ne_succd : i.1 ≠ d + 1 := by omega
      have hd_ne_zero : d ≠ 0 := by omega
      simp [lowerBoundChainGradient, lowerBoundChainEdge, lowerBoundChainNode,
        PiLp.toLp_apply, hprev, hi_last, hi_ne_zero, hi_ne_succd,
        hd_ne_zero]
      left
      ring_nf
  · have hi_zero : i.1 = 0 := by omega
    by_cases hnext : i.1 + 1 < d
    · have hd_ne_zero : d ≠ 0 := by omega
      have hd_ne_one : d ≠ 1 := by omega
      have hone_lt_d : 1 < d := by omega
      simp [lowerBoundChainGradient, lowerBoundChainEdge, lowerBoundChainNode,
        PiLp.toLp_apply, hi_zero, hd_ne_zero, hd_ne_one]
      left
      simp [hone_lt_d]
      ring_nf
    · have hd_eq : d = 1 := by omega
      simp [lowerBoundChainGradient, lowerBoundChainEdge, lowerBoundChainNode,
        PiLp.toLp_apply, hi_zero, hd_eq]
      left
      ring_nf

/--
The displayed support calculation in Chewi's proof of Theorem 4.4: if
`x ∈ V_k`, then the tridiagonal-chain gradient belongs to `V_{k+1}`.
-/
theorem lowerBoundChainGradient_mem_coordinatePrefixSubmodule
    {d k : ℕ} {beta : ℝ} {x : EuclideanSpace ℝ (Fin d)}
    (hx : x ∈ coordinatePrefixSubmodule d k) :
    lowerBoundChainGradient beta d x ∈ coordinatePrefixSubmodule d (k + 1) := by
  intro i hi
  have hpos : 0 < i.1 := by omega
  have hxi : x i = 0 := hx i (by omega)
  have hprev :
      x ⟨i.1 - 1, lt_of_le_of_lt (Nat.sub_le i.1 1) i.2⟩ = 0 := by
    apply hx
    change k ≤ i.1 - 1
    omega
  by_cases hnext : i.1 + 1 < d
  · have hnext_zero : x ⟨i.1 + 1, hnext⟩ = 0 := by
      apply hx
      change k ≤ i.1 + 1
      omega
    simp [lowerBoundChainGradient, PiLp.toLp_apply, hpos, hnext, hxi,
      hprev, hnext_zero]
  · simp [lowerBoundChainGradient, PiLp.toLp_apply, hpos, hnext, hxi, hprev]

/--
The lower-bound quadratic supplies the support hypothesis needed by the
abstract `V_n` induction.
-/
theorem gradientSpanTrajectory_mem_coordinatePrefixSubmodule_of_lowerBoundChainGradient
    {d : ℕ} {beta : ℝ} {x : ℕ -> EuclideanSpace ℝ (Fin d)}
    (hx0 : x 0 = 0)
    (hspan : IsGradientSpanTrajectory (lowerBoundChainGradient beta d) x) :
    ∀ n, x n ∈ coordinatePrefixSubmodule d n :=
  gradientSpanTrajectory_mem_coordinatePrefixSubmodule_of_grad_mem_next
    hx0 hspan (fun _ hxk =>
      lowerBoundChainGradient_mem_coordinatePrefixSubmodule hxk)

/--
The source minimizer candidate for the tridiagonal chain system:
`x_*[k] = 1 - k / (d + 1)` in one-based coordinates.
-/
noncomputable def lowerBoundChainMinimizer (d : ℕ) :
    EuclideanSpace ℝ (Fin d) :=
  WithLp.toLp 2 fun i : Fin d =>
    1 - ((i.1 : ℝ) + 1) / ((d : ℝ) + 1)

/-- The tridiagonal chain-gradient vanishes at Chewi's displayed minimizer. -/
theorem lowerBoundChainGradient_lowerBoundChainMinimizer
    (beta : ℝ) (d : ℕ) :
    lowerBoundChainGradient beta d (lowerBoundChainMinimizer d) = 0 := by
  ext i
  have hden : ((d : ℝ) + 1) ≠ 0 := by positivity
  by_cases hprev : 0 < i.1
  · have hprev_cast : (((i.1 - 1 : ℕ) : ℝ) + 1) = (i.1 : ℝ) := by
      have hle : 1 ≤ i.1 := hprev
      rw [Nat.cast_sub hle]
      ring
    by_cases hnext : i.1 + 1 < d
    · simp [lowerBoundChainGradient, lowerBoundChainMinimizer, PiLp.toLp_apply,
        hprev, hnext]
      field_simp [hden]
      ring_nf
      simp
    · have hi_eq : i.1 + 1 = d := by omega
      have hi_cast : (i.1 : ℝ) + 1 = (d : ℝ) := by
        exact_mod_cast hi_eq
      simp [lowerBoundChainGradient, lowerBoundChainMinimizer, PiLp.toLp_apply,
        hprev, hnext]
      rw [hi_cast]
      field_simp [hden]
      ring_nf
      right
      nlinarith
  · have hi_zero : i.1 = 0 := by omega
    by_cases hnext : i.1 + 1 < d
    · have hnext_one : 1 < d := by omega
      simp [lowerBoundChainGradient, lowerBoundChainMinimizer, PiLp.toLp_apply,
        hi_zero, hnext_one]
      field_simp [hden]
      ring_nf
      simp
    · have hd_eq : d = 1 := by omega
      simp [lowerBoundChainGradient, lowerBoundChainMinimizer, PiLp.toLp_apply,
        hi_zero, hd_eq]
      ring_nf
      simp

/-- Each coordinate of Chewi's displayed minimizer is nonnegative. -/
theorem lowerBoundChainMinimizer_coord_nonneg (d : ℕ) (i : Fin d) :
    0 ≤ lowerBoundChainMinimizer d i := by
  have hdenpos : 0 < (d : ℝ) + 1 := by positivity
  have hlt : (i.1 : ℝ) < (d : ℝ) := by exact_mod_cast i.2
  have hfrac_le_one :
      ((i.1 : ℝ) + 1) / ((d : ℝ) + 1) ≤ 1 := by
    rw [div_le_one hdenpos]
    nlinarith
  simp [lowerBoundChainMinimizer, PiLp.toLp_apply]
  nlinarith

/-- Each coordinate of Chewi's displayed minimizer is at most one. -/
theorem lowerBoundChainMinimizer_coord_le_one (d : ℕ) (i : Fin d) :
    lowerBoundChainMinimizer d i ≤ 1 := by
  have hfrac_nonneg :
      0 ≤ ((i.1 : ℝ) + 1) / ((d : ℝ) + 1) := by positivity
  simp [lowerBoundChainMinimizer, PiLp.toLp_apply]
  nlinarith

/-- The coordinates of Chewi's displayed minimizer have square at most one. -/
theorem lowerBoundChainMinimizer_coord_sq_le_one (d : ℕ) (i : Fin d) :
    (lowerBoundChainMinimizer d i) ^ (2 : ℕ) ≤ 1 := by
  have hnonneg := lowerBoundChainMinimizer_coord_nonneg d i
  have hle := lowerBoundChainMinimizer_coord_le_one d i
  have hsquare :
      (lowerBoundChainMinimizer d i) ^ (2 : ℕ) ≤ (1 : ℝ) ^ (2 : ℕ) :=
    (sq_le_sq₀ hnonneg zero_le_one).2 hle
  simpa using hsquare

/-- Chewi's displayed minimizer satisfies the source estimate `‖x_*‖² ≤ d`. -/
theorem lowerBoundChainMinimizer_norm_sq_le_dim (d : ℕ) :
    ‖lowerBoundChainMinimizer d‖ ^ (2 : ℕ) ≤ (d : ℝ) := by
  rw [EuclideanSpace.real_norm_sq_eq]
  calc
    (∑ i : Fin d, (lowerBoundChainMinimizer d i) ^ (2 : ℕ))
        ≤ ∑ _i : Fin d, (1 : ℝ) := by
          exact Finset.sum_le_sum fun i _hi =>
            lowerBoundChainMinimizer_coord_sq_le_one d i
    _ = (d : ℝ) := by
      simp [Finset.sum_const, nsmul_eq_mul]

/--
At Chewi's displayed minimizer, every extended chain node lies on the straight
line from `1` to `0`.
-/
theorem lowerBoundChainNode_lowerBoundChainMinimizer
    (d : ℕ) (j : Fin (d + 2)) :
    lowerBoundChainNode d (lowerBoundChainMinimizer d) j =
      1 - (j.1 : ℝ) / ((d : ℝ) + 1) := by
  by_cases hzero : j.1 = 0
  · simp [lowerBoundChainNode, hzero]
  · by_cases hlast : j.1 = d + 1
    · have hden : ((d : ℝ) + 1) ≠ 0 := by positivity
      simp [lowerBoundChainNode, hlast]
      field_simp [hden]
      ring
    · have hjpos : 1 ≤ j.1 := by omega
      have hcast : (((j.1 - 1 : ℕ) : ℝ) + 1) = (j.1 : ℝ) := by
        rw [Nat.cast_sub hjpos]
        ring
      simp [lowerBoundChainNode, lowerBoundChainMinimizer, hzero, hlast,
        PiLp.toLp_apply]
      rw [hcast]

/-- Every edge difference at Chewi's displayed minimizer is `-1 / (d + 1)`. -/
theorem lowerBoundChainEdge_lowerBoundChainMinimizer
    (d : ℕ) (k : Fin (d + 1)) :
    lowerBoundChainEdge d (lowerBoundChainMinimizer d) k =
      -(1 / ((d : ℝ) + 1)) := by
  have hden : ((d : ℝ) + 1) ≠ 0 := by positivity
  unfold lowerBoundChainEdge
  rw [lowerBoundChainNode_lowerBoundChainMinimizer,
    lowerBoundChainNode_lowerBoundChainMinimizer]
  simp
  field_simp [hden]
  ring

/-- Exact value of Chewi's lower-bound quadratic at the displayed minimizer. -/
theorem lowerBoundChainObjective_lowerBoundChainMinimizer
    (beta : ℝ) (d : ℕ) :
    lowerBoundChainObjective beta d (lowerBoundChainMinimizer d) =
      beta / (8 * ((d : ℝ) + 1)) := by
  have hden : ((d : ℝ) + 1) ≠ 0 := by positivity
  simp [lowerBoundChainObjective, lowerBoundChainEdge_lowerBoundChainMinimizer,
    Finset.sum_const, nsmul_eq_mul]
  field_simp [hden]

/--
Cauchy's inequality applied to the boundary chain: the squared edge energy is at
least the squared total drop divided by the number of edges.
-/
theorem lowerBoundChain_edgeSquareSum_ge (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) :
    (1 : ℝ) / ((d : ℝ) + 1) ≤
      ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) := by
  have hcs :
      (∑ k : Fin (d + 1), lowerBoundChainEdge d x k) ^ (2 : ℕ) ≤
        ((d : ℝ) + 1) *
          ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) := by
    simpa [Finset.card_univ, Fintype.card_fin, Nat.cast_add, Nat.cast_one]
      using
        (sq_sum_le_card_mul_sum_sq (s := Finset.univ)
          (f := fun k : Fin (d + 1) => lowerBoundChainEdge d x k))
  have hsquare :
      (1 : ℝ) ≤
        ((d : ℝ) + 1) *
          ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) := by
    simpa [lowerBoundChainEdge_sum d x] using hcs
  have hdenpos : 0 < (d : ℝ) + 1 := by positivity
  exact (div_le_iff₀ hdenpos).mpr (by simpa [mul_comm] using hsquare)

/-- Global lower bound for Chewi's shifted tridiagonal lower-bound objective. -/
theorem lowerBoundChainObjective_ge_minValue {beta : ℝ} (hbeta : 0 ≤ beta)
    (d : ℕ) (x : EuclideanSpace ℝ (Fin d)) :
    beta / (8 * ((d : ℝ) + 1)) ≤
      lowerBoundChainObjective beta d x := by
  have henergy := lowerBoundChain_edgeSquareSum_ge d x
  have hcoef : 0 ≤ beta / 8 := div_nonneg hbeta (by norm_num)
  have hmul := mul_le_mul_of_nonneg_left henergy hcoef
  have hdenpos : 0 < (d : ℝ) + 1 := by positivity
  calc
    beta / (8 * ((d : ℝ) + 1))
        = (beta / 8) * (1 / ((d : ℝ) + 1)) := by
            field_simp [hdenpos.ne']
    _ ≤ (beta / 8) *
          ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) := hmul
    _ = lowerBoundChainObjective beta d x := by
          rw [lowerBoundChainObjective]

/-- Chewi's displayed chain point globally minimizes the shifted objective. -/
theorem lowerBoundChainObjective_isMinOn_lowerBoundChainMinimizer
    {beta : ℝ} (hbeta : 0 ≤ beta) (d : ℕ) :
    IsMinOn (lowerBoundChainObjective beta d) Set.univ
      (lowerBoundChainMinimizer d) := by
  rw [isMinOn_univ_iff]
  intro y
  rw [lowerBoundChainObjective_lowerBoundChainMinimizer]
  exact lowerBoundChainObjective_ge_minValue hbeta d y

/-- Exact source value of Chewi's unshifted quadratic at the displayed minimizer. -/
theorem lowerBoundChainTextbookObjective_lowerBoundChainMinimizer
    (beta : ℝ) (d : ℕ) :
    lowerBoundChainTextbookObjective beta d (lowerBoundChainMinimizer d) =
      -(beta / 8) * (1 - 1 / ((d : ℝ) + 1)) := by
  have hden : ((d : ℝ) + 1) ≠ 0 := by positivity
  rw [lowerBoundChainTextbookObjective,
    lowerBoundChainObjective_lowerBoundChainMinimizer]
  field_simp [hden]
  ring

/-- Global source lower bound for Chewi's unshifted lower-bound objective. -/
theorem lowerBoundChainTextbookObjective_ge_minValue
    {beta : ℝ} (hbeta : 0 ≤ beta) (d : ℕ)
    (x : EuclideanSpace ℝ (Fin d)) :
    -(beta / 8) * (1 - 1 / ((d : ℝ) + 1)) ≤
      lowerBoundChainTextbookObjective beta d x := by
  rw [lowerBoundChainTextbookObjective]
  rw [← lowerBoundChainTextbookObjective_lowerBoundChainMinimizer]
  simp [lowerBoundChainTextbookObjective]
  rw [lowerBoundChainObjective_lowerBoundChainMinimizer]
  exact lowerBoundChainObjective_ge_minValue hbeta d x

/-- Chewi's displayed point globally minimizes the unshifted textbook objective. -/
theorem lowerBoundChainTextbookObjective_isMinOn_lowerBoundChainMinimizer
    {beta : ℝ} (hbeta : 0 ≤ beta) (d : ℕ) :
    IsMinOn (lowerBoundChainTextbookObjective beta d) Set.univ
      (lowerBoundChainMinimizer d) := by
  rw [isMinOn_univ_iff]
  intro y
  rw [lowerBoundChainTextbookObjective_lowerBoundChainMinimizer]
  exact lowerBoundChainTextbookObjective_ge_minValue hbeta d y

/--
If a point lies in the discovered-coordinate subspace `V_n`, then the first
`n + 1` chain edges already telescope from boundary value `1` to `0`.
-/
theorem lowerBoundChain_prefixEdge_sum_of_mem_coordinatePrefixSubmodule
    {n d : ℕ} (hnd : n ≤ d) {x : EuclideanSpace ℝ (Fin d)}
    (hx : x ∈ coordinatePrefixSubmodule d n) :
    (∑ k : Fin (n + 1), lowerBoundChainEdge d x ⟨k.1, by omega⟩) = -1 := by
  have htel := finSum_forwardDifference n
    (fun j : Fin (n + 2) => lowerBoundChainNode d x ⟨j.1, by omega⟩)
  have hnode_end : lowerBoundChainNode d x ⟨n + 1, by omega⟩ = 0 := by
    by_cases hnd_eq : n = d
    · have hlast : n + 1 = d + 1 := by omega
      simp [lowerBoundChainNode, hlast]
    · have hnlt : n < d := lt_of_le_of_ne hnd hnd_eq
      have hxcoord : x ⟨n, hnlt⟩ = 0 := hx ⟨n, hnlt⟩ le_rfl
      simp [lowerBoundChainNode, hxcoord]
  have htel' :
      (∑ k : Fin (n + 1), lowerBoundChainEdge d x ⟨k.1, by omega⟩) =
        lowerBoundChainNode d x ⟨n + 1, by omega⟩ -
          lowerBoundChainNode d x ⟨0, by omega⟩ := by
    simpa [lowerBoundChainEdge, Fin.val_last] using htel
  rw [hnode_end] at htel'
  simpa [lowerBoundChainNode] using htel'

/--
Cauchy lower bound for the first `n + 1` edge residuals of a point in `V_n`.
-/
theorem lowerBoundChain_prefixEdgeSquareSum_ge_of_mem_coordinatePrefixSubmodule
    {n d : ℕ} (hnd : n ≤ d) {x : EuclideanSpace ℝ (Fin d)}
    (hx : x ∈ coordinatePrefixSubmodule d n) :
    (1 : ℝ) / ((n : ℝ) + 1) ≤
      ∑ k : Fin (n + 1),
        (lowerBoundChainEdge d x ⟨k.1, by omega⟩) ^ (2 : ℕ) := by
  have hcs :
      (∑ k : Fin (n + 1), lowerBoundChainEdge d x ⟨k.1, by omega⟩) ^
          (2 : ℕ) ≤
        ((n : ℝ) + 1) *
          ∑ k : Fin (n + 1),
            (lowerBoundChainEdge d x ⟨k.1, by omega⟩) ^ (2 : ℕ) := by
    simpa [Finset.card_univ, Fintype.card_fin, Nat.cast_add, Nat.cast_one]
      using
        (sq_sum_le_card_mul_sum_sq (s := Finset.univ)
          (f := fun k : Fin (n + 1) =>
            lowerBoundChainEdge d x ⟨k.1, by omega⟩))
  have hsquare :
      (1 : ℝ) ≤
        ((n : ℝ) + 1) *
          ∑ k : Fin (n + 1),
            (lowerBoundChainEdge d x ⟨k.1, by omega⟩) ^ (2 : ℕ) := by
    simpa [lowerBoundChain_prefixEdge_sum_of_mem_coordinatePrefixSubmodule
      hnd hx] using hcs
  have hdenpos : 0 < (n : ℝ) + 1 := by positivity
  exact (div_le_iff₀ hdenpos).mpr (by simpa [mul_comm] using hsquare)

/-- The first `n + 1` edge-energy terms are bounded by the full chain energy. -/
theorem lowerBoundChain_prefixEdgeSquareSum_le_full
    {n d : ℕ} (hnd : n ≤ d) (x : EuclideanSpace ℝ (Fin d)) :
    (∑ k : Fin (n + 1),
        (lowerBoundChainEdge d x ⟨k.1, by omega⟩) ^ (2 : ℕ)) ≤
      ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) := by
  let emb : Fin (n + 1) ↪ Fin (d + 1) :=
    { toFun := fun k => ⟨k.1, by omega⟩
      inj' := by
        intro a b hab
        ext
        exact congrArg (fun k : Fin (d + 1) => k.1) hab }
  let g : Fin (d + 1) -> ℝ :=
    fun k => (lowerBoundChainEdge d x k) ^ (2 : ℕ)
  change (∑ k : Fin (n + 1), g (emb k)) ≤ ∑ k : Fin (d + 1), g k
  rw [← Finset.sum_map (Finset.univ : Finset (Fin (n + 1))) emb g]
  exact Finset.sum_le_sum_of_subset_of_nonneg (by simp)
    (fun k _ _ => sq_nonneg (lowerBoundChainEdge d x k))

/--
The source step `f_d = f_n` on `V_n`, packaged as the lower bound it supplies:
any point in `V_n` has full `d`-chain objective at least the `n`-chain minimum.
-/
theorem lowerBoundChainObjective_ge_prefixMin_of_mem_coordinatePrefixSubmodule
    {beta : ℝ} (hbeta : 0 ≤ beta) {n d : ℕ} (hnd : n ≤ d)
    {x : EuclideanSpace ℝ (Fin d)}
    (hx : x ∈ coordinatePrefixSubmodule d n) :
    beta / (8 * ((n : ℝ) + 1)) ≤
      lowerBoundChainObjective beta d x := by
  have hprefix :
      (1 : ℝ) / ((n : ℝ) + 1) ≤
        ∑ k : Fin (n + 1),
          (lowerBoundChainEdge d x ⟨k.1, by omega⟩) ^ (2 : ℕ) :=
    lowerBoundChain_prefixEdgeSquareSum_ge_of_mem_coordinatePrefixSubmodule
      hnd hx
  have hfull :
      (1 : ℝ) / ((n : ℝ) + 1) ≤
        ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) :=
    hprefix.trans (lowerBoundChain_prefixEdgeSquareSum_le_full hnd x)
  have hcoef : 0 ≤ beta / 8 := div_nonneg hbeta (by norm_num)
  have hmul := mul_le_mul_of_nonneg_left hfull hcoef
  have hdenpos : 0 < (n : ℝ) + 1 := by positivity
  calc
    beta / (8 * ((n : ℝ) + 1))
        = (beta / 8) * (1 / ((n : ℝ) + 1)) := by
            field_simp [hdenpos.ne']
    _ ≤ (beta / 8) *
          ∑ k : Fin (d + 1), (lowerBoundChainEdge d x k) ^ (2 : ℕ) := hmul
    _ = lowerBoundChainObjective beta d x := by
          rw [lowerBoundChainObjective]

/--
The main finite-dimensional gap estimate in Chewi Theorem 4.4 before choosing
`d` as a multiple of `N`.
-/
theorem lowerBoundChainObjective_gap_ge_of_gradientSpanTrajectory
    {beta : ℝ} (hbeta : 0 ≤ beta) {N d : ℕ} (hNd : N ≤ d)
    {x : ℕ -> EuclideanSpace ℝ (Fin d)}
    (hx0 : x 0 = 0)
    (hspan : IsGradientSpanTrajectory (lowerBoundChainGradient beta d) x) :
    beta / (8 * ((N : ℝ) + 1)) -
        beta / (8 * ((d : ℝ) + 1)) ≤
      lowerBoundChainObjective beta d (x N) -
        lowerBoundChainObjective beta d (lowerBoundChainMinimizer d) := by
  have hxN : x N ∈ coordinatePrefixSubmodule d N :=
    gradientSpanTrajectory_mem_coordinatePrefixSubmodule_of_lowerBoundChainGradient
      hx0 hspan N
  have hprefix :
      beta / (8 * ((N : ℝ) + 1)) ≤
        lowerBoundChainObjective beta d (x N) :=
    lowerBoundChainObjective_ge_prefixMin_of_mem_coordinatePrefixSubmodule
      hbeta hNd hxN
  rw [lowerBoundChainObjective_lowerBoundChainMinimizer]
  linarith

/--
Source-shaped Theorem 4.4 corollary from the common choice `d = 2N + 1`.
-/
theorem lowerBoundChainObjective_gap_ge_two_mul_add_one
    {beta : ℝ} (hbeta : 0 ≤ beta) (N : ℕ)
    {x : ℕ -> EuclideanSpace ℝ (Fin (2 * N + 1))}
    (hx0 : x 0 = 0)
    (hspan :
      IsGradientSpanTrajectory (lowerBoundChainGradient beta (2 * N + 1)) x) :
    beta / (16 * ((N : ℝ) + 1)) ≤
      lowerBoundChainObjective beta (2 * N + 1) (x N) -
        lowerBoundChainObjective beta (2 * N + 1)
          (lowerBoundChainMinimizer (2 * N + 1)) := by
  have hgap :=
    lowerBoundChainObjective_gap_ge_of_gradientSpanTrajectory
      (beta := beta) hbeta (N := N) (d := 2 * N + 1) (by omega)
      hx0 hspan
  have hleft :
      beta / (8 * ((N : ℝ) + 1)) -
          beta / (8 * (((2 * N + 1 : ℕ) : ℝ) + 1)) =
        beta / (16 * ((N : ℝ) + 1)) := by
    have hden : ((N : ℝ) + 1) ≠ 0 := by positivity
    have hden2 : (((2 * N + 1 : ℕ) : ℝ) + 1) ≠ 0 := by positivity
    field_simp [hden, hden2]
    norm_num [Nat.cast_add, Nat.cast_mul]
    ring
  rw [← hleft]
  exact hgap

/-- Source-objective version of the finite-dimensional Theorem 4.4 gap estimate. -/
theorem lowerBoundChainTextbookObjective_gap_ge_of_gradientSpanTrajectory
    {beta : ℝ} (hbeta : 0 ≤ beta) {N d : ℕ} (hNd : N ≤ d)
    {x : ℕ -> EuclideanSpace ℝ (Fin d)}
    (hx0 : x 0 = 0)
    (hspan : IsGradientSpanTrajectory (lowerBoundChainGradient beta d) x) :
    beta / (8 * ((N : ℝ) + 1)) -
        beta / (8 * ((d : ℝ) + 1)) ≤
      lowerBoundChainTextbookObjective beta d (x N) -
        lowerBoundChainTextbookObjective beta d (lowerBoundChainMinimizer d) := by
  rw [lowerBoundChainTextbookObjective_gap_eq_objective_gap]
  exact lowerBoundChainObjective_gap_ge_of_gradientSpanTrajectory
    hbeta hNd hx0 hspan

/-- Source-objective `d = 2N + 1` corollary for Chewi Theorem 4.4. -/
theorem lowerBoundChainTextbookObjective_gap_ge_two_mul_add_one
    {beta : ℝ} (hbeta : 0 ≤ beta) (N : ℕ)
    {x : ℕ -> EuclideanSpace ℝ (Fin (2 * N + 1))}
    (hx0 : x 0 = 0)
    (hspan :
      IsGradientSpanTrajectory (lowerBoundChainGradient beta (2 * N + 1)) x) :
    beta / (16 * ((N : ℝ) + 1)) ≤
      lowerBoundChainTextbookObjective beta (2 * N + 1) (x N) -
        lowerBoundChainTextbookObjective beta (2 * N + 1)
          (lowerBoundChainMinimizer (2 * N + 1)) := by
  rw [lowerBoundChainTextbookObjective_gap_eq_objective_gap]
  exact lowerBoundChainObjective_gap_ge_two_mul_add_one hbeta N hx0 hspan

end CoordinatePrefix

end Optimization
end StatInference
