import StatInference.Optimization.Basic

/-!
# Gradient-span algorithms

This module starts the Chapter 4 lower-bound layer for Chewi's optimization
notes.  It records Definition 4.3 in a reusable form and proves the immediate
source example: every fixed-step gradient-descent trajectory is a gradient-span
trajectory.
-/

namespace StatInference
namespace Optimization

open Set
open scoped InnerProductSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/--
The linear span of the gradients queried through time `n`.

This is the subspace appearing in Chewi Definition 4.3:
`span {grad (x 0), ..., grad (x n)}`.
-/
def gradientSpanSubmodule (grad : E -> E) (x : ℕ -> E)
    (n : ℕ) : Submodule ℝ E :=
  Submodule.span ℝ ((fun k : ℕ => grad (x k)) '' {k : ℕ | k ≤ n})

/-- The affine space `x_0 + span {grad (x 0), ..., grad (x n)}`. -/
def affineGradientSpan (grad : E -> E) (x : ℕ -> E) (n : ℕ) : Set E :=
  {y | y - x 0 ∈ gradientSpanSubmodule grad x n}

/--
Chewi Definition 4.3, specialized to deterministic sequences generated from
an explicit gradient oracle.

The condition `x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n` is the vector
space form of `x_{n+1} ∈ x_0 + span {grad f(x_0), ..., grad f(x_n)}`.
-/
def IsGradientSpanTrajectory (grad : E -> E) (x : ℕ -> E) : Prop :=
  ∀ n, x (n + 1) ∈ affineGradientSpan grad x n

/-- Unfolding helper for the affine-gradient-span display. -/
theorem mem_affineGradientSpan_iff {grad : E -> E} {x : ℕ -> E}
    {n : ℕ} {y : E} :
    y ∈ affineGradientSpan grad x n ↔
      y - x 0 ∈ gradientSpanSubmodule grad x n :=
  Iff.rfl

/-- Each queried gradient belongs to the gradient span through its query time. -/
theorem gradient_mem_gradientSpanSubmodule (grad : E -> E) (x : ℕ -> E)
    (n : ℕ) :
    grad (x n) ∈ gradientSpanSubmodule grad x n := by
  exact Submodule.subset_span ⟨n, by simp, rfl⟩

/-- The gradient spans are monotone in the number of allowed oracle queries. -/
theorem gradientSpanSubmodule_mono (grad : E -> E) (x : ℕ -> E)
    {m n : ℕ} (hmn : m ≤ n) :
    gradientSpanSubmodule grad x m ≤ gradientSpanSubmodule grad x n := by
  refine Submodule.span_mono ?_
  rintro v ⟨k, hk, rfl⟩
  exact ⟨k, hk.trans hmn, rfl⟩

/--
One gradient-descent step preserves membership in the affine space generated by
the gradients seen so far.
-/
theorem gradientDescentStep_sub_initial_mem_gradientSpanSubmodule
    (grad : E -> E) (x : ℕ -> E) (h : ℝ) (n : ℕ)
    (hprev : x n - x 0 ∈ gradientSpanSubmodule grad x n) :
    gradientDescentStep grad h (x n) - x 0 ∈
      gradientSpanSubmodule grad x n := by
  have hgrad :
      grad (x n) ∈ gradientSpanSubmodule grad x n :=
    gradient_mem_gradientSpanSubmodule grad x n
  have hstep :
      (x n - x 0) - h • grad (x n) ∈
        gradientSpanSubmodule grad x n :=
    Submodule.sub_mem _ hprev (Submodule.smul_mem _ h hgrad)
  simpa [gradientDescentStep, sub_eq_add_neg, add_assoc, add_left_comm,
    add_comm] using hstep

/-- The source example after Definition 4.3: fixed-step GD is gradient-span. -/
theorem IsGradientDescentTrajectory.isGradientSpanTrajectory
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) :
    IsGradientSpanTrajectory grad x := by
  intro n
  change x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n
  induction n with
  | zero =>
      have hgrad :
          grad (x 0) ∈ gradientSpanSubmodule grad x 0 :=
        gradient_mem_gradientSpanSubmodule grad x 0
      have hmem :
          (-h) • grad (x 0) ∈ gradientSpanSubmodule grad x 0 :=
        Submodule.smul_mem _ (-h) hgrad
      simpa [hx 0, gradientDescentStep, sub_eq_add_neg, neg_smul, add_assoc,
        add_left_comm, add_comm] using hmem
  | succ n ih =>
      have hprev :
          x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x (n + 1) :=
        gradientSpanSubmodule_mono grad x (Nat.le_succ n) ih
      have hstep :
          gradientDescentStep grad h (x (n + 1)) - x 0 ∈
            gradientSpanSubmodule grad x (n + 1) :=
        gradientDescentStep_sub_initial_mem_gradientSpanSubmodule
          grad x h (n + 1) hprev
      simpa [Nat.succ_eq_add_one, add_assoc, hx (n + 1)] using hstep

/--
Convenience wrapper for the textbook display:
`x_{n+1} - x_0` lies in the span of gradients through time `n` for GD.
-/
theorem gradientDescentTrajectory_mem_gradientSpanSubmodule
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) (n : ℕ) :
    x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n :=
  hx.isGradientSpanTrajectory n

/--
Source-shaped affine version of the GD example:
`x_{n+1} ∈ x_0 + span {grad (x_0), ..., grad (x_n)}`.
-/
theorem gradientDescentTrajectory_mem_affineGradientSpan
    {grad : E -> E} {h : ℝ} {x : ℕ -> E}
    (hx : IsGradientDescentTrajectory grad h x) (n : ℕ) :
    x (n + 1) ∈ affineGradientSpan grad x n :=
  hx.isGradientSpanTrajectory n

section CoordinatePrefix

/--
The coordinate prefix subspace used in Chewi's proof of Theorem 4.4.

In zero-based `Fin d` coordinates, this is the source subspace
`V_n = {x : x[k] = 0 for k = n + 1, ..., d}`: the coordinates with
`n <= i.val` vanish.
-/
def coordinatePrefixSubmodule (d n : ℕ) :
    Submodule ℝ (EuclideanSpace ℝ (Fin d)) where
  carrier := {x | ∀ i : Fin d, n ≤ i.1 -> x i = 0}
  zero_mem' := by
    intro i hi
    rfl
  add_mem' := by
    intro x y hx hy i hi
    simp [hx i hi, hy i hi]
  smul_mem' := by
    intro a x hx i hi
    simp [hx i hi]

/-- Membership in the coordinate-prefix subspace is just coordinate vanishing. -/
theorem mem_coordinatePrefixSubmodule_iff {d n : ℕ}
    {x : EuclideanSpace ℝ (Fin d)} :
    x ∈ coordinatePrefixSubmodule d n ↔
      ∀ i : Fin d, n ≤ i.1 -> x i = 0 :=
  Iff.rfl

/-- The source subspaces `V_n` are monotone in `n`. -/
theorem coordinatePrefixSubmodule_mono (d : ℕ) {m n : ℕ} (hmn : m ≤ n) :
    coordinatePrefixSubmodule d m ≤ coordinatePrefixSubmodule d n := by
  intro x hx i hi
  exact hx i (hmn.trans hi)

/-- Once the prefix length reaches the dimension, the coordinate subspace is all space. -/
theorem coordinatePrefixSubmodule_eq_top_of_le {d n : ℕ} (hdn : d ≤ n) :
    coordinatePrefixSubmodule d n = ⊤ := by
  ext x
  constructor
  · intro hx
    exact Submodule.mem_top
  · intro hx i hi
    exact (Nat.not_lt_of_ge (hdn.trans hi) i.2).elim

/--
If every queried gradient through time `n` lies in `V_{n+1}`, then the
gradient span through time `n` is contained in `V_{n+1}`.
-/
theorem gradientSpanSubmodule_le_coordinatePrefixSubmodule
    {d : ℕ}
    {grad : EuclideanSpace ℝ (Fin d) -> EuclideanSpace ℝ (Fin d)}
    {x : ℕ -> EuclideanSpace ℝ (Fin d)} {n : ℕ}
    (hgrad : ∀ ⦃k : ℕ⦄, k ≤ n ->
      grad (x k) ∈ coordinatePrefixSubmodule d (n + 1)) :
    gradientSpanSubmodule grad x n ≤ coordinatePrefixSubmodule d (n + 1) := by
  refine Submodule.span_le.mpr ?_
  rintro v ⟨k, hk, rfl⟩
  exact hgrad hk

/--
Abstract induction in Chewi Theorem 4.4: if the oracle gradients satisfy
`grad (x_k) ∈ V_{k+1}` along a gradient-span trajectory starting from zero,
then every iterate satisfies `x_n ∈ V_n`.
-/
theorem gradientSpanTrajectory_mem_coordinatePrefixSubmodule_of_grad_mem_next
    {d : ℕ}
    {grad : EuclideanSpace ℝ (Fin d) -> EuclideanSpace ℝ (Fin d)}
    {x : ℕ -> EuclideanSpace ℝ (Fin d)}
    (hx0 : x 0 = 0)
    (hspan : IsGradientSpanTrajectory grad x)
    (hgrad : ∀ k, x k ∈ coordinatePrefixSubmodule d k ->
      grad (x k) ∈ coordinatePrefixSubmodule d (k + 1)) :
    ∀ n, x n ∈ coordinatePrefixSubmodule d n := by
  intro n
  induction n using Nat.strong_induction_on with
  | h n ih =>
      cases n with
      | zero =>
          simp [hx0, coordinatePrefixSubmodule]
      | succ n =>
          have hspan_n :
              x (n + 1) - x 0 ∈ gradientSpanSubmodule grad x n :=
            mem_affineGradientSpan_iff.mp (hspan n)
          have hle :
              gradientSpanSubmodule grad x n ≤
                coordinatePrefixSubmodule d (n + 1) := by
            refine gradientSpanSubmodule_le_coordinatePrefixSubmodule ?_
            intro k hk
            have hxk : x k ∈ coordinatePrefixSubmodule d k :=
              ih k (Nat.lt_succ_of_le hk)
            exact coordinatePrefixSubmodule_mono d (Nat.succ_le_succ hk)
              (hgrad k hxk)
          have hx_sub :
              x (n + 1) - x 0 ∈ coordinatePrefixSubmodule d (n + 1) :=
            hle hspan_n
          simpa [hx0] using hx_sub

end CoordinatePrefix

end Optimization
end StatInference
