import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.MeasureTheory.MeasurableSpace.Pi

/-!
# Generated sigma-field wrappers

This module records Billingsley-facing support wrappers around generated
measurable spaces, pi-systems, and measure extensionality.  These are reusable
in source crosswalks for extension/uniqueness arguments while keeping mathlib
as the proof authority.
-/

namespace StatInference
namespace ProbabilityMeasure

open MeasureTheory

universe u v

/-- The measurable space generated by a collection of sets. -/
@[reducible]
def GeneratedSigma (Ω : Type u) (C : Set (Set Ω)) : MeasurableSpace Ω :=
  MeasurableSpace.generateFrom C

/-- A generator set is measurable in its generated sigma-field. -/
theorem generatedSigma_measurableSet_of_mem
    {Ω : Type u} {C : Set (Set Ω)} {s : Set Ω} (hs : s ∈ C) :
    @MeasurableSet Ω (GeneratedSigma Ω C) s := by
  exact MeasurableSpace.measurableSet_generateFrom hs

/-- Generated sigma-fields are the least measurable spaces containing the generators. -/
theorem generatedSigma_le
    {Ω : Type u} [mΩ : MeasurableSpace Ω] {C : Set (Set Ω)}
    (hC : ∀ s ∈ C, MeasurableSet s) :
    GeneratedSigma Ω C ≤ mΩ := by
  exact MeasurableSpace.generateFrom_le hC

/-- A function into a generated sigma-field is measurable if all generator preimages are. -/
theorem measurable_generatedSigma
    {Ω : Type u} [MeasurableSpace Ω] {S : Type v} {C : Set (Set S)}
    {f : Ω -> S}
    (hf : ∀ t ∈ C, MeasurableSet (f ⁻¹' t)) :
    @Measurable Ω S _ (GeneratedSigma S C) f := by
  exact measurable_generateFrom hf

/--
Finite-measure uniqueness on a pi-system generating the measurable space.
This is a Billingsley-facing wrapper over `MeasureTheory.ext_of_generate_finite`.
-/
theorem measure_ext_of_generate_finite
    {Ω : Type u} [mΩ : MeasurableSpace Ω] {μ ν : Measure Ω}
    (C : Set (Set Ω)) (hΩ : mΩ = GeneratedSigma Ω C) (hC : IsPiSystem C)
    [IsFiniteMeasure μ]
    (hμν : ∀ s ∈ C, μ s = ν s) (h_univ : μ Set.univ = ν Set.univ) :
    μ = ν := by
  exact MeasureTheory.ext_of_generate_finite C hΩ hC hμν h_univ

/-- The coercion from probability measures to measures is injective. -/
theorem probabilityMeasure_toMeasure_injective
    {Ω : Type u} [MeasurableSpace Ω] :
    Function.Injective ((↑) : MeasureTheory.ProbabilityMeasure Ω -> Measure Ω) := by
  exact MeasureTheory.ProbabilityMeasure.toMeasure_injective

/-- Probability measures are equal if their underlying measures agree on measurable sets. -/
theorem probabilityMeasure_eq_of_forall_toMeasure_apply_eq
    {Ω : Type u} [MeasurableSpace Ω]
    (μ ν : MeasureTheory.ProbabilityMeasure Ω)
    (h : ∀ s : Set Ω, MeasurableSet s -> (μ : Measure Ω) s = (ν : Measure Ω) s) :
    μ = ν := by
  exact MeasureTheory.ProbabilityMeasure.eq_of_forall_toMeasure_apply_eq μ ν h

/-- Probability measures are equal if their probability values agree on measurable sets. -/
theorem probabilityMeasure_eq_of_forall_apply_eq
    {Ω : Type u} [MeasurableSpace Ω]
    (μ ν : MeasureTheory.ProbabilityMeasure Ω)
    (h : ∀ s : Set Ω, MeasurableSet s -> μ s = ν s) :
    μ = ν := by
  exact MeasureTheory.ProbabilityMeasure.eq_of_forall_apply_eq μ ν h

/--
Probability-measure uniqueness on a pi-system generating the measurable space.
The total-mass hypothesis is discharged by probability normalization.
-/
theorem probabilityMeasure_ext_of_generate_finite_toMeasure
    {Ω : Type u} [mΩ : MeasurableSpace Ω]
    (μ ν : MeasureTheory.ProbabilityMeasure Ω)
    (C : Set (Set Ω)) (hΩ : mΩ = GeneratedSigma Ω C) (hC : IsPiSystem C)
    (hμν : ∀ s ∈ C, (μ : Measure Ω) s = (ν : Measure Ω) s) :
    μ = ν := by
  apply MeasureTheory.ProbabilityMeasure.toMeasure_injective
  exact MeasureTheory.ext_of_generate_finite C hΩ hC hμν (by simp)

/--
Probability-measure uniqueness from equality of probability values on a generating pi-system.
This is the probability-value version of
`probabilityMeasure_ext_of_generate_finite_toMeasure`.
-/
theorem probabilityMeasure_ext_of_generate_finite
    {Ω : Type u} [mΩ : MeasurableSpace Ω]
    (μ ν : MeasureTheory.ProbabilityMeasure Ω)
    (C : Set (Set Ω)) (hΩ : mΩ = GeneratedSigma Ω C) (hC : IsPiSystem C)
    (hμν : ∀ s ∈ C, μ s = ν s) :
    μ = ν := by
  exact probabilityMeasure_ext_of_generate_finite_toMeasure μ ν C hΩ hC fun s hs => by
    simpa [MeasureTheory.ProbabilityMeasure.ennreal_coeFn_eq_coeFn_toMeasure] using
      congr_arg (fun x : NNReal => (x : ENNReal)) (hμν s hs)

/-- The measurable sets form a pi-system. -/
theorem isPiSystem_measurableSet
    {Ω : Type u} [MeasurableSpace Ω] :
    IsPiSystem {s : Set Ω | MeasurableSet s} := by
  exact MeasurableSpace.isPiSystem_measurableSet

/-- Pi-systems are closed under product generators. -/
theorem isPiSystem_pi
    {ι : Type u} {S : ι -> Type v} {C : ∀ i, Set (Set (S i))}
    (hC : ∀ i, IsPiSystem (C i)) :
    IsPiSystem (Set.pi Set.univ '' Set.pi Set.univ C) := by
  exact IsPiSystem.pi hC

/-- The product of generated sigma-fields is generated by product generators. -/
theorem pi_generatedSigma_eq
    {ι : Type u} {S : ι -> Type v} [Finite ι]
    {C : ∀ i, Set (Set (S i))}
    (hC : ∀ i, IsCountablySpanning (C i)) :
    (@MeasurableSpace.pi ι S fun i => GeneratedSigma (S i) (C i)) =
      GeneratedSigma ((i : ι) -> S i) (Set.pi Set.univ '' Set.pi Set.univ C) := by
  exact generateFrom_pi_eq hC

end ProbabilityMeasure
end StatInference
