import StatInference.AsymptoticStatistics.Basic
import StatInference.ProbabilityMeasure.StrongLaw
import Mathlib.Analysis.Calculus.InverseFunctionTheorem.FDeriv

/-!
# van der Vaart 1998 Chapter 4 moment-estimator interfaces

This module starts the source-shaped Chapter 4 lane for A. W. van der Vaart,
*Asymptotic Statistics* (1998), Section 4.1.  The first layer packages the
method-of-moments asymptotic-normality proof as the handoff used in the text:
an empirical-moment CLT followed by the Chapter 3 delta method applied to the
local inverse of the theoretical moment map.
-/

noncomputable section

namespace StatInference
namespace AsymptoticStatistics

open Filter MeasureTheory ProbabilityTheory
open scoped BigOperators Real Topology

universe u v w x

/-- The textbook rate `sqrt n` tends to infinity. -/
theorem vaart1998_sqrt_nat_tendsto_atTop :
    Tendsto (fun n : ℕ => √(n : ℝ)) atTop atTop :=
  Real.tendsto_sqrt_atTop.comp tendsto_natCast_atTop_atTop

/--
Local inverse data for van der Vaart Theorem 4.1.

The textbook obtains these fields from the inverse function theorem.  Keeping
them as a certificate lets the Chapter 4 asymptotic-normality proof compile
while later work fills in the inverse-function and existence-with-probability
layers separately.
-/
structure Vaart1998MomentLocalInverseCertificate (M Θ : Type*)
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [MeasurableSpace Θ] where
  /-- The theoretical moment map `e(theta) = P_theta f`. -/
  e : Θ -> M
  /-- A local inverse of the theoretical moment map near `eta0`. -/
  eInv : M -> Θ
  /-- The true theoretical moment, `e theta0`. -/
  eta0 : M
  /-- The true parameter. -/
  theta0 : Θ
  /-- The derivative of the local inverse at `eta0`. -/
  Dinv : M →L[ℝ] Θ
  /-- The source identity `eta0 = e theta0`, oriented for rewriting moments. -/
  eta0_eq : e theta0 = eta0
  /-- The local inverse sends the true moment back to the true parameter. -/
  inverse_at_eta0 : eInv eta0 = theta0
  /-- Differentiability of the local inverse, supplied by the inverse function theorem. -/
  inverse_deriv : HasFDerivAt eInv Dinv eta0
  /-- Measurability needed to discharge the Chapter 3 delta-method remainder. -/
  inverse_measurable : Measurable eInv

/--
Inverse-function-theorem bridge into the Vaart Theorem 4.1 local inverse
certificate.

Mathlib constructs a local inverse and proves its derivative from a strict
derivative with continuous-linear equivalence derivative.  Global measurability
of this chosen local inverse is kept as an explicit field because the inverse
function theorem supplies local continuity at the true moment.
-/
def vaart1998_momentLocalInverseCertificate_of_hasStrictFDerivAt
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    [MeasurableSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    (hInv_meas : Measurable (he.localInverse e De theta0)) :
    Vaart1998MomentLocalInverseCertificate M Θ where
  e := e
  eInv := he.localInverse e De theta0
  eta0 := e theta0
  theta0 := theta0
  Dinv := (De.symm : M →L[ℝ] Θ)
  eta0_eq := rfl
  inverse_at_eta0 := he.localInverse_apply_image
  inverse_deriv := he.to_localInverse.hasFDerivAt
  inverse_measurable := hInv_meas

/--
Local range data for the moment equations in van der Vaart Theorem 4.1.

The source proof obtains a neighborhood `V` of the true moment such that the
local inverse is defined on `V`.  This certificate records only the deterministic
equation-solving facts that later probability/localization work needs.
-/
structure Vaart1998MomentLocalRangeCertificate (M Θ : Type*) where
  /-- The theoretical moment map `e(theta) = P_theta f`. -/
  e : Θ -> M
  /-- The local inverse on the moment range. -/
  eInv : M -> Θ
  /-- Local range of empirical moments where the estimator exists. -/
  momentRange : Set M
  /-- Local parameter domain where uniqueness is asserted. -/
  parameterDomain : Set Θ
  /-- The inverse candidate maps local moments into the local parameter domain. -/
  eInv_mem_parameterDomain : ∀ {m : M}, m ∈ momentRange -> eInv m ∈ parameterDomain
  /-- Right inverse property: the local-inverse estimator solves the moment equation. -/
  right_inverse_on_momentRange : ∀ {m : M}, m ∈ momentRange -> e (eInv m) = m
  /-- Left inverse property on the local parameter domain, used for uniqueness. -/
  left_inverse_on_parameterDomain :
    ∀ {theta : Θ}, theta ∈ parameterDomain -> eInv (e theta) = theta

/--
Canonical local-range certificate generated by mathlib's local inverse.

The range/domain sets are chosen to be exactly the points where the right and
left inverse identities hold.  Later packets can replace these tautological
sets with open neighborhoods from the inverse function theorem.
-/
def vaart1998_momentLocalRangeCertificate_of_hasStrictFDerivAt
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0) :
    Vaart1998MomentLocalRangeCertificate M Θ where
  e := e
  eInv := he.localInverse e De theta0
  momentRange := {m : M | e (he.localInverse e De theta0 m) = m}
  parameterDomain := {theta : Θ | he.localInverse e De theta0 (e theta) = theta}
  eInv_mem_parameterDomain := by
    intro m hmem
    change he.localInverse e De theta0
        (e (he.localInverse e De theta0 m)) =
      he.localInverse e De theta0 m
    rw [hmem]
  right_inverse_on_momentRange := by
    intro m hmem
    exact hmem
  left_inverse_on_parameterDomain := by
    intro theta htheta
    exact htheta

/--
The inverse-function-theorem source neighborhood for the true parameter is open.

This records the exact local parameter domain supplied by mathlib's
`OpenPartialHomeomorph`, matching the open neighborhood `U` in van der Vaart's
proof of Theorem 4.1.
-/
theorem vaart1998_hasStrictFDerivAt_open_local_parameterDomain
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0) :
    IsOpen (he.toOpenPartialHomeomorph e).source :=
  (he.toOpenPartialHomeomorph e).open_source

/--
The inverse-function-theorem target neighborhood for the true moment is open.

This records the exact local moment range supplied by mathlib's
`OpenPartialHomeomorph`, matching the open neighborhood `V` in van der Vaart's
proof of Theorem 4.1.
-/
theorem vaart1998_hasStrictFDerivAt_open_local_momentRange
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0) :
    IsOpen (he.toOpenPartialHomeomorph e).target :=
  (he.toOpenPartialHomeomorph e).open_target

/--
The true parameter belongs to the inverse-function-theorem local source
neighborhood.
-/
theorem vaart1998_hasStrictFDerivAt_theta0_mem_local_parameterDomain
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0) :
    theta0 ∈ (he.toOpenPartialHomeomorph e).source :=
  he.mem_toOpenPartialHomeomorph_source

/--
The true theoretical moment belongs to the inverse-function-theorem local
target neighborhood.
-/
theorem vaart1998_hasStrictFDerivAt_eta0_mem_local_momentRange
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0) :
    e theta0 ∈ (he.toOpenPartialHomeomorph e).target :=
  he.image_mem_toOpenPartialHomeomorph_target

/--
Open-neighborhood local-range certificate generated by mathlib's inverse
function theorem.

Unlike the tautological identity-validity constructor above, this version uses
the actual open source and target of `he.toOpenPartialHomeomorph e` as the
local parameter domain and local moment range.  This is the deterministic
`U`/`V` bridge in van der Vaart's proof of Theorem 4.1.
-/
def vaart1998_momentLocalRangeCertificate_of_hasStrictFDerivAt_openPartialHomeomorph
    {M Θ : Type*}
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0) :
    Vaart1998MomentLocalRangeCertificate M Θ where
  e := e
  eInv := (he.toOpenPartialHomeomorph e).symm
  momentRange := (he.toOpenPartialHomeomorph e).target
  parameterDomain := (he.toOpenPartialHomeomorph e).source
  eInv_mem_parameterDomain := by
    intro m hmem
    exact (he.toOpenPartialHomeomorph e).map_target hmem
  right_inverse_on_momentRange := by
    intro m hmem
    simpa using (he.toOpenPartialHomeomorph e).right_inv hmem
  left_inverse_on_parameterDomain := by
    intro theta htheta
    simpa using (he.toOpenPartialHomeomorph e).left_inv htheta

/--
Supplied probability-localization certificate for Theorem 4.1's existence
sentence.  The vector LLN should eventually discharge `localRange_probability`;
for now it is kept as an explicit field.
-/
structure Vaart1998MomentEstimatorLocalRangeProbabilityCertificate
    (Ω M : Type*) [MeasurableSpace Ω] (P : Measure Ω) where
  empiricalMoment : ℕ -> Ω -> M
  momentRange : Set M
  localRange_probability :
    Tendsto (fun n : ℕ => P.real {ω : Ω | empiricalMoment n ω ∈ momentRange})
      atTop (𝓝 1)

/--
Open-neighborhood localization from convergence in probability.

If empirical moments converge in probability to the true moment and the local
moment range is an open neighborhood of that true moment, then the empirical
moments lie in the local range with probability tending to one.  This is the
probability skeleton of the existence sentence in van der Vaart Theorem 4.1;
the vector LLN is the intended downstream source of `hconv`.
-/
theorem vaart1998_local_range_probability_of_tendstoInMeasure_const
    {Ω M : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    [PseudoMetricSpace M] [MeasurableSpace M] [OpensMeasurableSpace M]
    {empiricalMoment : ℕ -> Ω -> M} {eta0 : M} {momentRange : Set M}
    (hOpen : IsOpen momentRange) (heta0 : eta0 ∈ momentRange)
    (hconv : TendstoInMeasure P empiricalMoment atTop (fun _ : Ω => eta0))
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n)) :
    Tendsto (fun n : ℕ =>
      P.real {ω : Ω | empiricalMoment n ω ∈ momentRange}) atTop (𝓝 1) := by
  rcases Metric.mem_nhds_iff.mp (hOpen.mem_nhds heta0) with
    ⟨ε, hε, hball_subset⟩
  have htail :
      Tendsto (fun n : ℕ =>
        P.real {ω : Ω | ε ≤ dist (empiricalMoment n ω) eta0}) atTop
          (𝓝 0) := by
    simpa using
      (MeasureTheory.tendstoInMeasure_iff_measureReal_dist.mp hconv ε hε)
  have hlower_tendsto :
      Tendsto (fun n : ℕ =>
        (1 : ℝ) - P.real {ω : Ω | ε ≤ dist (empiricalMoment n ω) eta0})
          atTop (𝓝 1) := by
    simpa using (tendsto_const_nhds.sub htail)
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le
    hlower_tendsto tendsto_const_nhds ?_ ?_
  · intro n
    let event : Set Ω := {ω : Ω | empiricalMoment n ω ∈ momentRange}
    let tail : Set Ω := {ω : Ω | ε ≤ dist (empiricalMoment n ω) eta0}
    have hevent_meas : MeasurableSet event := by
      dsimp [event]
      exact (hmeas n) hOpen.measurableSet
    have hcompl_subset_tail : eventᶜ ⊆ tail := by
      intro ω hω
      dsimp [event, tail] at hω ⊢
      by_contra hdist
      have hdist_lt : dist (empiricalMoment n ω) eta0 < ε :=
        lt_of_not_ge hdist
      have hball_mem : empiricalMoment n ω ∈ Metric.ball eta0 ε := by
        rw [Metric.mem_ball]
        simpa [dist_comm] using hdist_lt
      exact hω (hball_subset hball_mem)
    have hcompl_le : P.real eventᶜ ≤ P.real tail :=
      measureReal_mono hcompl_subset_tail
    have hsum : P.real event + P.real eventᶜ = 1 :=
      probReal_add_probReal_compl (μ := P) hevent_meas
    have hsub_eq : 1 - P.real eventᶜ = P.real event := by
      linarith
    calc
      (1 : ℝ) - P.real tail ≤ 1 - P.real eventᶜ := sub_le_sub_left hcompl_le 1
      _ = P.real event := hsub_eq
  · intro n
    have hle :
        P.real {ω : Ω | empiricalMoment n ω ∈ momentRange} ≤
          P.real Set.univ :=
      measureReal_mono (μ := P) (Set.subset_univ _)
    simpa using hle

/--
Certificate constructor for the Theorem 4.1 local-range probability field from
convergence in probability to the true moment and an open local range.
-/
def vaart1998_momentEstimatorLocalRangeProbabilityCertificate_of_tendstoInMeasure
    {Ω M : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    [PseudoMetricSpace M] [MeasurableSpace M] [OpensMeasurableSpace M]
    (empiricalMoment : ℕ -> Ω -> M) {eta0 : M} (momentRange : Set M)
    (hOpen : IsOpen momentRange) (heta0 : eta0 ∈ momentRange)
    (hconv : TendstoInMeasure P empiricalMoment atTop (fun _ : Ω => eta0))
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n)) :
    Vaart1998MomentEstimatorLocalRangeProbabilityCertificate Ω M P where
  empiricalMoment := empiricalMoment
  momentRange := momentRange
  localRange_probability :=
    vaart1998_local_range_probability_of_tendstoInMeasure_const
      hOpen heta0 hconv hmeas

/--
Almost-sure empirical-moment convergence implies convergence in probability.

This is the method-of-moments LLN handoff: any strong-law theorem that proves
almost-sure convergence of the empirical moment vector to the true moment can
now feed the Chapter 4 local existence machinery.
-/
theorem vaart1998_empiricalMoment_tendstoInMeasure_of_ae_tendsto_const
    {Ω M : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P] [PseudoEMetricSpace M]
    {empiricalMoment : ℕ -> Ω -> M} {eta0 : M}
    (hstrong : ∀ n : ℕ, AEStronglyMeasurable (empiricalMoment n) P)
    (hAE : ∀ᵐ ω ∂P,
      Tendsto (fun n : ℕ => empiricalMoment n ω) atTop (𝓝 eta0)) :
    TendstoInMeasure P empiricalMoment atTop (fun _ : Ω => eta0) :=
  vaart1998_tendstoInMeasure_of_tendsto_ae hstrong hAE

/--
Finite-coordinate empirical-moment strong-law handoff.

For finitely many real moment coordinates, the local real-valued strong law
implies almost-sure convergence of the vector of empirical moments to the
vector of population moments.
-/
theorem vaart1998_finiteCoordinate_empiricalMoment_tendsto_ae_real
    {Coordinate Ω : Type*} [Fintype Coordinate] [MeasurableSpace Ω]
    {P : Measure Ω}
    (X : Coordinate -> ℕ -> Ω -> ℝ)
    (hX_integrable : ∀ coordinate, Integrable (X coordinate 0) P)
    (hX_indep :
      ∀ coordinate, Pairwise fun i j =>
        _root_.ProbabilityTheory.IndepFun (X coordinate i) (X coordinate j) P)
    (hX_ident :
      ∀ coordinate i, IdentDistrib (X coordinate i) (X coordinate 0) P P) :
    ∀ᵐ ω ∂P,
      Tendsto
        (fun n : ℕ => fun coordinate : Coordinate =>
          (∑ i ∈ Finset.range n, X coordinate i ω) / n)
        atTop
        (𝓝 fun coordinate : Coordinate => ∫ ω, X coordinate 0 ω ∂P) := by
  have hcenter :=
    StatInference.ProbabilityMeasure.finite_centeredStrongLaw_ae_real
      X hX_integrable hX_indep hX_ident
  filter_upwards [hcenter] with ω hω
  rw [tendsto_pi_nhds]
  intro coordinate
  have hcoord := hω coordinate
  have hconst :
      Tendsto
        (fun _n : ℕ => ∫ sample, X coordinate 0 sample ∂P)
        atTop (𝓝 (∫ sample, X coordinate 0 sample ∂P)) :=
    tendsto_const_nhds
  simpa using hcoord.add hconst

/--
Finite-coordinate empirical-moment convergence in probability.

The only extra input beyond the finite-coordinate strong law is the standard
strong measurability of the vector empirical moment sequence.
-/
theorem vaart1998_finiteCoordinate_empiricalMoment_tendstoInMeasure_real
    {Coordinate Ω : Type*} [Fintype Coordinate] [MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P]
    (X : Coordinate -> ℕ -> Ω -> ℝ)
    (hX_integrable : ∀ coordinate, Integrable (X coordinate 0) P)
    (hX_indep :
      ∀ coordinate, Pairwise fun i j =>
        _root_.ProbabilityTheory.IndepFun (X coordinate i) (X coordinate j) P)
    (hX_ident :
      ∀ coordinate i, IdentDistrib (X coordinate i) (X coordinate 0) P P)
    (hstrong : ∀ n : ℕ,
      AEStronglyMeasurable
        (fun ω : Ω => fun coordinate : Coordinate =>
          (∑ i ∈ Finset.range n, X coordinate i ω) / n) P) :
    TendstoInMeasure P
      (fun n : ℕ => fun ω : Ω => fun coordinate : Coordinate =>
        (∑ i ∈ Finset.range n, X coordinate i ω) / n)
      atTop
      (fun _ : Ω => fun coordinate : Coordinate =>
        ∫ sample, X coordinate 0 sample ∂P) :=
  vaart1998_empiricalMoment_tendstoInMeasure_of_ae_tendsto_const
    hstrong
    (vaart1998_finiteCoordinate_empiricalMoment_tendsto_ae_real
      X hX_integrable hX_indep hX_ident)

/--
Local-range probability certificate from almost-sure empirical-moment
convergence to the true moment.
-/
def vaart1998_momentEstimatorLocalRangeProbabilityCertificate_of_ae_tendsto
    {Ω M : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [PseudoMetricSpace M] [MeasurableSpace M] [OpensMeasurableSpace M]
    (empiricalMoment : ℕ -> Ω -> M) {eta0 : M} (momentRange : Set M)
    (hOpen : IsOpen momentRange) (heta0 : eta0 ∈ momentRange)
    (hstrong : ∀ n : ℕ, AEStronglyMeasurable (empiricalMoment n) P)
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n))
    (hAE : ∀ᵐ ω ∂P,
      Tendsto (fun n : ℕ => empiricalMoment n ω) atTop (𝓝 eta0)) :
    Vaart1998MomentEstimatorLocalRangeProbabilityCertificate Ω M P :=
  vaart1998_momentEstimatorLocalRangeProbabilityCertificate_of_tendstoInMeasure
    empiricalMoment momentRange hOpen heta0
    (vaart1998_empiricalMoment_tendstoInMeasure_of_ae_tendsto_const
      hstrong hAE)
    hmeas

/--
Open inverse-function-theorem local-range probability.

This specializes the open-neighborhood localization lemma to the target
neighborhood produced by `HasStrictFDerivAt.toOpenPartialHomeomorph`.
-/
theorem vaart1998_theorem_4_1_open_local_range_probability_of_hasStrictFDerivAt
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [OpensMeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    {empiricalMoment : ℕ -> Ω -> M}
    (hconv : TendstoInMeasure P empiricalMoment atTop (fun _ : Ω => e theta0))
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n)) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          empiricalMoment n ω ∈ (he.toOpenPartialHomeomorph e).target})
        atTop (𝓝 1) :=
  vaart1998_local_range_probability_of_tendstoInMeasure_const
    (hOpen := (he.toOpenPartialHomeomorph e).open_target)
    (heta0 := he.image_mem_toOpenPartialHomeomorph_target)
    hconv hmeas

/--
Local-range probability certificate generated from the inverse function theorem
and convergence in probability of empirical moments to the true moment.
-/
def vaart1998_momentEstimatorLocalRangeProbabilityCertificate_of_hasStrictFDerivAt_tendstoInMeasure
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [OpensMeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    (empiricalMoment : ℕ -> Ω -> M)
    (hconv : TendstoInMeasure P empiricalMoment atTop (fun _ : Ω => e theta0))
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n)) :
    Vaart1998MomentEstimatorLocalRangeProbabilityCertificate Ω M P where
  empiricalMoment := empiricalMoment
  momentRange := (he.toOpenPartialHomeomorph e).target
  localRange_probability :=
    vaart1998_theorem_4_1_open_local_range_probability_of_hasStrictFDerivAt
      e De he hconv hmeas

/--
Open inverse-function-theorem local-range probability from almost-sure
empirical-moment convergence.
-/
theorem vaart1998_theorem_4_1_open_local_range_probability_of_hasStrictFDerivAt_ae_tendsto
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [OpensMeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    {empiricalMoment : ℕ -> Ω -> M}
    (hstrong : ∀ n : ℕ, AEStronglyMeasurable (empiricalMoment n) P)
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n))
    (hAE : ∀ᵐ ω ∂P,
      Tendsto (fun n : ℕ => empiricalMoment n ω) atTop (𝓝 (e theta0))) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          empiricalMoment n ω ∈ (he.toOpenPartialHomeomorph e).target})
        atTop (𝓝 1) :=
  vaart1998_theorem_4_1_open_local_range_probability_of_hasStrictFDerivAt
    e De he
    (vaart1998_empiricalMoment_tendstoInMeasure_of_ae_tendsto_const
      hstrong hAE)
    hmeas

/--
Local-range probability certificate from strict differentiability and
almost-sure empirical-moment convergence.
-/
def vaart1998_momentEstimatorLocalRangeProbabilityCertificate_of_hasStrictFDerivAt_ae_tendsto
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [OpensMeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    (empiricalMoment : ℕ -> Ω -> M)
    (hstrong : ∀ n : ℕ, AEStronglyMeasurable (empiricalMoment n) P)
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n))
    (hAE : ∀ᵐ ω ∂P,
      Tendsto (fun n : ℕ => empiricalMoment n ω) atTop (𝓝 (e theta0))) :
    Vaart1998MomentEstimatorLocalRangeProbabilityCertificate Ω M P :=
  vaart1998_momentEstimatorLocalRangeProbabilityCertificate_of_hasStrictFDerivAt_tendstoInMeasure
    e De he empiricalMoment
    (vaart1998_empiricalMoment_tendstoInMeasure_of_ae_tendsto_const
      hstrong hAE)
    hmeas

/--
If the empirical moment lies in the local range, the inverse candidate solves
the moment equation.
-/
theorem vaart1998_theorem_4_1_moment_estimator_solves_on_local_range
    {Ω M Θ : Type*} (C : Vaart1998MomentLocalRangeCertificate M Θ)
    {empiricalMoment : ℕ -> Ω -> M} {n : ℕ} {ω : Ω}
    (hmem : empiricalMoment n ω ∈ C.momentRange) :
    C.e (C.eInv (empiricalMoment n ω)) = empiricalMoment n ω :=
  C.right_inverse_on_momentRange hmem

/--
Pointwise version for a named estimator that is definitionally or propositionally
equal to the local-inverse candidate on the given sample point.
-/
theorem vaart1998_theorem_4_1_moment_estimator_thetaHat_solves_on_local_range
    {Ω M Θ : Type*} (C : Vaart1998MomentLocalRangeCertificate M Θ)
    {empiricalMoment : ℕ -> Ω -> M} {thetaHat : ℕ -> Ω -> Θ}
    {n : ℕ} {ω : Ω}
    (hhat : thetaHat n ω = C.eInv (empiricalMoment n ω))
    (hmem : empiricalMoment n ω ∈ C.momentRange) :
    C.e (thetaHat n ω) = empiricalMoment n ω := by
  rw [hhat]
  exact vaart1998_theorem_4_1_moment_estimator_solves_on_local_range C hmem

/--
Uniqueness of the local moment-equation solution inside the supplied local
parameter domain.
-/
theorem vaart1998_theorem_4_1_moment_estimator_unique_on_parameterDomain
    {M Θ : Type*} (C : Vaart1998MomentLocalRangeCertificate M Θ)
    {m : M} {theta : Θ}
    (htheta : theta ∈ C.parameterDomain) (hsolve : C.e theta = m) :
    theta = C.eInv m := by
  have hleft := C.left_inverse_on_parameterDomain htheta
  rw [hsolve] at hleft
  exact hleft.symm

/--
The local-inverse candidate itself lies in the local parameter domain whenever
the empirical moment lies in the local range.
-/
theorem vaart1998_theorem_4_1_moment_estimator_mem_parameterDomain_on_local_range
    {Ω M Θ : Type*} (C : Vaart1998MomentLocalRangeCertificate M Θ)
    {empiricalMoment : ℕ -> Ω -> M} {n : ℕ} {ω : Ω}
    (hmem : empiricalMoment n ω ∈ C.momentRange) :
    C.eInv (empiricalMoment n ω) ∈ C.parameterDomain :=
  C.eInv_mem_parameterDomain hmem

/--
Certificate form of the Theorem 4.1 existence-localization sentence: empirical
moments fall in the local range with probability tending to one.
-/
theorem vaart1998_theorem_4_1_local_range_probability_of_certificate
    {Ω M : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    (C : Vaart1998MomentEstimatorLocalRangeProbabilityCertificate Ω M P) :
    Tendsto (fun n : ℕ =>
      P.real {ω : Ω | C.empiricalMoment n ω ∈ C.momentRange}) atTop (𝓝 1) :=
  C.localRange_probability

/--
If the local-range event has probability tending to one, then the local-inverse
candidate solves the moment equation with probability tending to one.
-/
theorem vaart1998_theorem_4_1_moment_equation_solved_with_probability_tending_to_one
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    (C : Vaart1998MomentLocalRangeCertificate M Θ)
    {empiricalMoment : ℕ -> Ω -> M}
    (hprob : Tendsto (fun n : ℕ =>
      P.real {ω : Ω | empiricalMoment n ω ∈ C.momentRange}) atTop (𝓝 1)) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          C.e (C.eInv (empiricalMoment n ω)) = empiricalMoment n ω})
        atTop (𝓝 1) := by
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le
    hprob tendsto_const_nhds ?_ ?_
  · intro n
    refine measureReal_mono ?_
    intro ω hmem
    exact C.right_inverse_on_momentRange hmem
  · intro n
    have hle :
        P.real
            {ω : Ω |
              C.e (C.eInv (empiricalMoment n ω)) = empiricalMoment n ω} ≤
          P.real Set.univ :=
      measureReal_mono (μ := P) (Set.subset_univ _)
    simpa using hle

/--
Certificate form of the moment-equation solved-with-probability statement.
-/
theorem vaart1998_theorem_4_1_moment_equation_solved_with_probability_tending_to_one_of_certificate
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    (C : Vaart1998MomentLocalRangeCertificate M Θ)
    (Pcert : Vaart1998MomentEstimatorLocalRangeProbabilityCertificate Ω M P)
    (hRange : Pcert.momentRange = C.momentRange) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          C.e (C.eInv (Pcert.empiricalMoment n ω)) =
            Pcert.empiricalMoment n ω})
        atTop (𝓝 1) :=
  vaart1998_theorem_4_1_moment_equation_solved_with_probability_tending_to_one
    (C := C) (empiricalMoment := Pcert.empiricalMoment) <| by
      simpa [hRange] using Pcert.localRange_probability

/--
The inverse-function theorem plus convergence in probability of empirical
moments yields a moment-equation solution with probability tending to one.
-/
theorem vaart1998_theorem_4_1_moment_equation_solved_with_probability_of_hasStrictFDerivAt_tendstoInMeasure
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [OpensMeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    {empiricalMoment : ℕ -> Ω -> M}
    (hconv : TendstoInMeasure P empiricalMoment atTop (fun _ : Ω => e theta0))
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n)) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          e ((he.toOpenPartialHomeomorph e).symm (empiricalMoment n ω)) =
            empiricalMoment n ω})
        atTop (𝓝 1) := by
  let C :=
    vaart1998_momentLocalRangeCertificate_of_hasStrictFDerivAt_openPartialHomeomorph
      e De he
  have hprob :
      Tendsto (fun n : ℕ =>
        P.real {ω : Ω | empiricalMoment n ω ∈ C.momentRange}) atTop
          (𝓝 1) := by
    simpa [C] using
      vaart1998_theorem_4_1_open_local_range_probability_of_hasStrictFDerivAt
        e De he hconv hmeas
  simpa [C] using
    vaart1998_theorem_4_1_moment_equation_solved_with_probability_tending_to_one
      (C := C) (empiricalMoment := empiricalMoment) hprob

/--
The inverse-function theorem plus almost-sure empirical-moment convergence
yields a moment-equation solution with probability tending to one.
-/
theorem vaart1998_theorem_4_1_moment_equation_solved_with_probability_of_hasStrictFDerivAt_ae_tendsto
    {Ω M Θ : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P]
    [NormedAddCommGroup M] [NormedSpace ℝ M] [MeasurableSpace M]
    [OpensMeasurableSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> M) {theta0 : Θ} (De : Θ ≃L[ℝ] M)
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] M) theta0)
    {empiricalMoment : ℕ -> Ω -> M}
    (hstrong : ∀ n : ℕ, AEStronglyMeasurable (empiricalMoment n) P)
    (hmeas : ∀ n : ℕ, Measurable (empiricalMoment n))
    (hAE : ∀ᵐ ω ∂P,
      Tendsto (fun n : ℕ => empiricalMoment n ω) atTop (𝓝 (e theta0))) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          e ((he.toOpenPartialHomeomorph e).symm (empiricalMoment n ω)) =
            empiricalMoment n ω})
        atTop (𝓝 1) :=
  vaart1998_theorem_4_1_moment_equation_solved_with_probability_of_hasStrictFDerivAt_tendstoInMeasure
    e De he
    (vaart1998_empiricalMoment_tendstoInMeasure_of_ae_tendsto_const
      hstrong hAE)
    hmeas

/--
Finite-coordinate strong-law version of the Theorem 4.1 local existence step.

For a finite real moment vector, coordinatewise iid strong laws feed the
inverse-function-theorem local range and imply that the local inverse candidate
solves the moment equation with probability tending to one.
-/
theorem vaart1998_theorem_4_1_moment_equation_solved_with_probability_of_hasStrictFDerivAt_finiteCoordinateStrongLaw_real
    {Coordinate Ω Θ : Type*} [Fintype Coordinate] [MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P]
    [MeasurableSpace (Coordinate -> ℝ)]
    [OpensMeasurableSpace (Coordinate -> ℝ)]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] [CompleteSpace Θ]
    (e : Θ -> Coordinate -> ℝ) {theta0 : Θ}
    (De : Θ ≃L[ℝ] (Coordinate -> ℝ))
    (he : HasStrictFDerivAt e (De : Θ →L[ℝ] (Coordinate -> ℝ)) theta0)
    (X : Coordinate -> ℕ -> Ω -> ℝ)
    (heta0 :
      e theta0 =
        (fun coordinate : Coordinate => ∫ sample, X coordinate 0 sample ∂P))
    (hX_integrable : ∀ coordinate, Integrable (X coordinate 0) P)
    (hX_indep :
      ∀ coordinate, Pairwise fun i j =>
        _root_.ProbabilityTheory.IndepFun (X coordinate i) (X coordinate j) P)
    (hX_ident :
      ∀ coordinate i, IdentDistrib (X coordinate i) (X coordinate 0) P P)
    (hstrong : ∀ n : ℕ,
      AEStronglyMeasurable
        (fun ω : Ω => fun coordinate : Coordinate =>
          (∑ i ∈ Finset.range n, X coordinate i ω) / n) P)
    (hmeas : ∀ n : ℕ,
      Measurable
        (fun ω : Ω => fun coordinate : Coordinate =>
          (∑ i ∈ Finset.range n, X coordinate i ω) / n)) :
    Tendsto (fun n : ℕ =>
      P.real
        {ω : Ω |
          e ((he.toOpenPartialHomeomorph e).symm
              (fun coordinate : Coordinate =>
                (∑ i ∈ Finset.range n, X coordinate i ω) / n)) =
            (fun coordinate : Coordinate =>
              (∑ i ∈ Finset.range n, X coordinate i ω) / n)})
        atTop (𝓝 1) :=
  vaart1998_theorem_4_1_moment_equation_solved_with_probability_of_hasStrictFDerivAt_tendstoInMeasure
    e De he
    (by
      simpa [heta0] using
        vaart1998_finiteCoordinate_empiricalMoment_tendstoInMeasure_real
          X hX_integrable hX_indep hX_ident hstrong)
    hmeas

/--
van der Vaart 1998, Theorem 4.1, method-of-moments delta handoff.

This theorem is the compiled Chapter 4 proof spine: once the empirical moments
have a scaled distributional limit and the local inverse of the theoretical
moment map is differentiable and measurable, the moment estimator inherits the
linear image limit by Theorem 3.1.
-/
theorem vaart1998_theorem_4_1_moment_estimator_delta_method
    {Ω : Type u} {Ω' : Type v} {M : Type w} {Θ : Type x}
    [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    [MeasurableSpace Ω'] {Q : Measure Ω'} [IsProbabilityMeasure Q]
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [MeasurableSpace M] [SecondCountableTopology M] [BorelSpace M]
    [OpensMeasurableSpace M] [CompleteSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ]
    [MeasurableSpace Θ] [SecondCountableTopology Θ] [BorelSpace Θ]
    [OpensMeasurableSpace Θ]
    {empiricalMoment : ℕ -> Ω -> M} {Z : Ω' -> M}
    {eInv : M -> Θ} {eta0 : M} {theta0 : Θ} {r : ℕ -> ℝ}
    (Dinv : M →L[ℝ] Θ)
    (hInv_deriv : HasFDerivAt eInv Dinv eta0)
    (hInv_meas : Measurable eInv)
    (heta0 : eInv eta0 = theta0)
    (hr : Tendsto r atTop atTop)
    (hCLT : TendstoInDistribution
      (fun n ω => r n • (empiricalMoment n ω - eta0)) atTop Z (fun _ => P) Q)
    (hEmpiricalMoment : ∀ n, AEMeasurable (empiricalMoment n) P) :
    TendstoInDistribution
      (fun n ω => r n • (eInv (empiricalMoment n ω) - theta0)) atTop
      (fun ω => Dinv (Z ω)) (fun _ => P) Q := by
  simpa [heta0] using
    vaart1998_theorem_3_1_delta_method_of_hasFDerivAt_distribution_measurable
      (Tn := empiricalMoment) (T := Z) (phi := eInv) (theta := eta0)
      (r := r) (L := Dinv) hInv_deriv hInv_meas hr hCLT
      hEmpiricalMoment

/--
van der Vaart 1998, Theorem 4.1, method-of-moments `sqrt n` form.

This is the same Chapter 4 handoff with the textbook rate fixed to `sqrt n`.
-/
theorem vaart1998_theorem_4_1_moment_estimator_sqrt_delta_method
    {Ω : Type u} {Ω' : Type v} {M : Type w} {Θ : Type x}
    [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    [MeasurableSpace Ω'] {Q : Measure Ω'} [IsProbabilityMeasure Q]
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [MeasurableSpace M] [SecondCountableTopology M] [BorelSpace M]
    [OpensMeasurableSpace M] [CompleteSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ]
    [MeasurableSpace Θ] [SecondCountableTopology Θ] [BorelSpace Θ]
    [OpensMeasurableSpace Θ]
    {empiricalMoment : ℕ -> Ω -> M} {Z : Ω' -> M}
    {eInv : M -> Θ} {eta0 : M} {theta0 : Θ}
    (Dinv : M →L[ℝ] Θ)
    (hInv_deriv : HasFDerivAt eInv Dinv eta0)
    (hInv_meas : Measurable eInv)
    (heta0 : eInv eta0 = theta0)
    (hCLT : TendstoInDistribution
      (fun (n : ℕ) ω => √(n : ℝ) • (empiricalMoment n ω - eta0)) atTop Z
        (fun _ => P) Q)
    (hEmpiricalMoment : ∀ n, AEMeasurable (empiricalMoment n) P) :
    TendstoInDistribution
      (fun (n : ℕ) ω => √(n : ℝ) • (eInv (empiricalMoment n ω) - theta0)) atTop
      (fun ω => Dinv (Z ω)) (fun _ => P) Q :=
  vaart1998_theorem_4_1_moment_estimator_delta_method
    (empiricalMoment := empiricalMoment) (Z := Z) (eInv := eInv)
    (eta0 := eta0) (theta0 := theta0)
    (r := fun n : ℕ => √(n : ℝ)) (Dinv := Dinv)
    hInv_deriv hInv_meas heta0 vaart1998_sqrt_nat_tendsto_atTop
    hCLT hEmpiricalMoment

/--
Certificate form of van der Vaart Theorem 4.1's delta-method step.
-/
theorem vaart1998_theorem_4_1_moment_estimator_delta_method_of_certificate
    {Ω : Type u} {Ω' : Type v} {M : Type w} {Θ : Type x}
    [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    [MeasurableSpace Ω'] {Q : Measure Ω'} [IsProbabilityMeasure Q]
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [MeasurableSpace M] [SecondCountableTopology M] [BorelSpace M]
    [OpensMeasurableSpace M] [CompleteSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ]
    [MeasurableSpace Θ] [SecondCountableTopology Θ] [BorelSpace Θ]
    [OpensMeasurableSpace Θ]
    (C : Vaart1998MomentLocalInverseCertificate M Θ)
    {empiricalMoment : ℕ -> Ω -> M} {Z : Ω' -> M} {r : ℕ -> ℝ}
    (hr : Tendsto r atTop atTop)
    (hCLT : TendstoInDistribution
      (fun n ω => r n • (empiricalMoment n ω - C.eta0)) atTop Z
        (fun _ => P) Q)
    (hEmpiricalMoment : ∀ n, AEMeasurable (empiricalMoment n) P) :
    TendstoInDistribution
      (fun n ω => r n • (C.eInv (empiricalMoment n ω) - C.theta0)) atTop
      (fun ω => C.Dinv (Z ω)) (fun _ => P) Q :=
  vaart1998_theorem_4_1_moment_estimator_delta_method
    (empiricalMoment := empiricalMoment) (Z := Z) (eInv := C.eInv)
    (eta0 := C.eta0) (theta0 := C.theta0) (r := r) (Dinv := C.Dinv)
    C.inverse_deriv C.inverse_measurable C.inverse_at_eta0 hr hCLT
    hEmpiricalMoment

/--
Textbook `sqrt n` certificate form of Theorem 4.1's delta-method step.
-/
theorem vaart1998_theorem_4_1_moment_estimator_sqrt_delta_method_of_certificate
    {Ω : Type u} {Ω' : Type v} {M : Type w} {Θ : Type x}
    [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    [MeasurableSpace Ω'] {Q : Measure Ω'} [IsProbabilityMeasure Q]
    [NormedAddCommGroup M] [NormedSpace ℝ M]
    [MeasurableSpace M] [SecondCountableTopology M] [BorelSpace M]
    [OpensMeasurableSpace M] [CompleteSpace M]
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ]
    [MeasurableSpace Θ] [SecondCountableTopology Θ] [BorelSpace Θ]
    [OpensMeasurableSpace Θ]
    (C : Vaart1998MomentLocalInverseCertificate M Θ)
    {empiricalMoment : ℕ -> Ω -> M} {Z : Ω' -> M}
    (hCLT : TendstoInDistribution
      (fun (n : ℕ) ω => √(n : ℝ) • (empiricalMoment n ω - C.eta0))
        atTop Z (fun _ => P) Q)
    (hEmpiricalMoment : ∀ n, AEMeasurable (empiricalMoment n) P) :
    TendstoInDistribution
      (fun (n : ℕ) ω => √(n : ℝ) • (C.eInv (empiricalMoment n ω) - C.theta0))
        atTop (fun ω => C.Dinv (Z ω)) (fun _ => P) Q :=
  vaart1998_theorem_4_1_moment_estimator_sqrt_delta_method
    (empiricalMoment := empiricalMoment) (Z := Z) (eInv := C.eInv)
    (eta0 := C.eta0) (theta0 := C.theta0) (Dinv := C.Dinv)
    C.inverse_deriv C.inverse_measurable C.inverse_at_eta0 hCLT
    hEmpiricalMoment

end AsymptoticStatistics
end StatInference
