import StatInference.Matching.WDSM.DiscretePATEBalancing
import StatInference.Matching.WDSM.DiscretePATTBalancing

/-!
# Score-measurable finite balancing algebra for WDSM

The previous finite balancing modules assume that a candidate score-cell mean
equals the true finite cell mean on each sample.  This module proves a concrete
source of that equality: if an outcome is exactly a function of the discrete
score cell on the finite sample, then its finite cell mean is that cell value.
-/

namespace StatInference
namespace Matching
namespace WDSM

variable {UnitA UnitB TargetUnit TreatedUnit ControlUnit Cell : Type*}
  [DecidableEq Cell]

/--
Finite score-measurable balancing theorem.  If two weighted samples have equal
normalized score-cell shares and their outcomes are both generated by the same
cell-value function, then their weighted sample means are equal.
-/
theorem weightedSampleMean_eq_of_scoreCellShare_eq_and_scoreMeasurable
    (sampleA : Finset UnitA) (sampleB : Finset UnitB)
    (cells : Finset Cell)
    (weightA : UnitA -> Real) (weightB : UnitB -> Real)
    (outcomeA : UnitA -> Real) (outcomeB : UnitB -> Real)
    (scoreA : UnitA -> Cell) (scoreB : UnitB -> Cell)
    (cellValue : Cell -> Real)
    (hcoverA : ∀ unit, unit ∈ sampleA -> scoreA unit ∈ cells)
    (hcoverB : ∀ unit, unit ∈ sampleB -> scoreB unit ∈ cells)
    (hmassA :
      ∀ cell, cell ∈ cells ->
        scoreCellMass sampleA weightA scoreA cell ≠ 0)
    (hmassB :
      ∀ cell, cell ∈ cells ->
        scoreCellMass sampleB weightB scoreB cell ≠ 0)
    (hshare :
      ∀ cell, cell ∈ cells ->
        scoreCellShare sampleA weightA scoreA cell =
          scoreCellShare sampleB weightB scoreB cell)
    (hscoreMeasA :
      ∀ unit, unit ∈ sampleA -> outcomeA unit = cellValue (scoreA unit))
    (hscoreMeasB :
      ∀ unit, unit ∈ sampleB -> outcomeB unit = cellValue (scoreB unit)) :
    weightedSampleMean sampleA weightA outcomeA =
      weightedSampleMean sampleB weightB outcomeB := by
  refine weightedSampleMean_eq_of_scoreCellShare_eq_and_candidateCellMean_eq
    sampleA sampleB cells weightA weightB outcomeA outcomeB scoreA scoreB
    cellValue hcoverA hcoverB hmassA hmassB hshare ?_ ?_
  · intro cell hcell
    exact (scoreCellMean_eq_const_of_eq_on_cell
      sampleA weightA outcomeA scoreA cell (cellValue cell)
      (hmassA cell hcell)
      (fun unit hunit hscore => by
        rw [hscoreMeasA unit hunit, hscore])).symm
  · intro cell hcell
    exact (scoreCellMean_eq_const_of_eq_on_cell
      sampleB weightB outcomeB scoreB cell (cellValue cell)
      (hmassB cell hcell)
      (fun unit hunit hscore => by
        rw [hscoreMeasB unit hunit, hscore])).symm

/--
Finite score-measurable PATE balancing theorem.  Treated and control observed
arm means identify the target finite PATE when each potential/observed outcome
is generated by the corresponding score-cell value function and the arm
score-cell shares match the target shares.
-/
theorem weightedSampleMeanContrast_eq_twoArmWeightedMeanContrast_of_scoreMeasurable
    (targetSample : Finset TargetUnit)
    (treatedSample : Finset TreatedUnit)
    (controlSample : Finset ControlUnit)
    (cells : Finset Cell)
    (targetWeight : TargetUnit -> Real)
    (treatedWeight : TreatedUnit -> Real)
    (controlWeight : ControlUnit -> Real)
    (targetOutcomeT targetOutcomeC : TargetUnit -> Real)
    (treatedOutcome : TreatedUnit -> Real)
    (controlOutcome : ControlUnit -> Real)
    (targetScore : TargetUnit -> Cell)
    (treatedScore : TreatedUnit -> Cell)
    (controlScore : ControlUnit -> Cell)
    (treatedCellValue controlCellValue : Cell -> Real)
    (hcoverTarget :
      ∀ unit, unit ∈ targetSample -> targetScore unit ∈ cells)
    (hcoverTreated :
      ∀ unit, unit ∈ treatedSample -> treatedScore unit ∈ cells)
    (hcoverControl :
      ∀ unit, unit ∈ controlSample -> controlScore unit ∈ cells)
    (hmassTarget :
      ∀ cell, cell ∈ cells ->
        scoreCellMass targetSample targetWeight targetScore cell ≠ 0)
    (hmassTreated :
      ∀ cell, cell ∈ cells ->
        scoreCellMass treatedSample treatedWeight treatedScore cell ≠ 0)
    (hmassControl :
      ∀ cell, cell ∈ cells ->
        scoreCellMass controlSample controlWeight controlScore cell ≠ 0)
    (hshareTreated :
      ∀ cell, cell ∈ cells ->
        scoreCellShare targetSample targetWeight targetScore cell =
          scoreCellShare treatedSample treatedWeight treatedScore cell)
    (hshareControl :
      ∀ cell, cell ∈ cells ->
        scoreCellShare targetSample targetWeight targetScore cell =
          scoreCellShare controlSample controlWeight controlScore cell)
    (hscoreMeasTargetT :
      ∀ unit, unit ∈ targetSample ->
        targetOutcomeT unit = treatedCellValue (targetScore unit))
    (hscoreMeasTreated :
      ∀ unit, unit ∈ treatedSample ->
        treatedOutcome unit = treatedCellValue (treatedScore unit))
    (hscoreMeasTargetC :
      ∀ unit, unit ∈ targetSample ->
        targetOutcomeC unit = controlCellValue (targetScore unit))
    (hscoreMeasControl :
      ∀ unit, unit ∈ controlSample ->
        controlOutcome unit = controlCellValue (controlScore unit)) :
    weightedSampleMeanContrast targetSample targetWeight
        targetOutcomeT targetOutcomeC =
      twoArmWeightedMeanContrast treatedSample controlSample
        treatedWeight controlWeight treatedOutcome controlOutcome := by
  have htreated :
      weightedSampleMean targetSample targetWeight targetOutcomeT =
        weightedSampleMean treatedSample treatedWeight treatedOutcome :=
    weightedSampleMean_eq_of_scoreCellShare_eq_and_scoreMeasurable
      targetSample treatedSample cells targetWeight treatedWeight
      targetOutcomeT treatedOutcome targetScore treatedScore treatedCellValue
      hcoverTarget hcoverTreated hmassTarget hmassTreated hshareTreated
      hscoreMeasTargetT hscoreMeasTreated
  have hcontrol :
      weightedSampleMean targetSample targetWeight targetOutcomeC =
        weightedSampleMean controlSample controlWeight controlOutcome :=
    weightedSampleMean_eq_of_scoreCellShare_eq_and_scoreMeasurable
      targetSample controlSample cells targetWeight controlWeight
      targetOutcomeC controlOutcome targetScore controlScore controlCellValue
      hcoverTarget hcoverControl hmassTarget hmassControl hshareControl
      hscoreMeasTargetC hscoreMeasControl
  unfold weightedSampleMeanContrast twoArmWeightedMeanContrast
  rw [htreated, hcontrol]

/--
Finite score-measurable PATT balancing theorem.  Only the target
counterfactual-control mean is transported from the control arm.
-/
theorem weightedSampleMeanContrast_eq_pattWeightedMeanContrast_of_scoreMeasurable_control
    (targetSample : Finset TargetUnit)
    (controlSample : Finset ControlUnit)
    (cells : Finset Cell)
    (targetWeight : TargetUnit -> Real)
    (controlWeight : ControlUnit -> Real)
    (treatedTargetOutcome targetControlOutcome : TargetUnit -> Real)
    (controlOutcome : ControlUnit -> Real)
    (targetScore : TargetUnit -> Cell)
    (controlScore : ControlUnit -> Cell)
    (controlCellValue : Cell -> Real)
    (hcoverTarget :
      ∀ unit, unit ∈ targetSample -> targetScore unit ∈ cells)
    (hcoverControl :
      ∀ unit, unit ∈ controlSample -> controlScore unit ∈ cells)
    (hmassTarget :
      ∀ cell, cell ∈ cells ->
        scoreCellMass targetSample targetWeight targetScore cell ≠ 0)
    (hmassControl :
      ∀ cell, cell ∈ cells ->
        scoreCellMass controlSample controlWeight controlScore cell ≠ 0)
    (hshareControl :
      ∀ cell, cell ∈ cells ->
        scoreCellShare targetSample targetWeight targetScore cell =
          scoreCellShare controlSample controlWeight controlScore cell)
    (hscoreMeasTargetControl :
      ∀ unit, unit ∈ targetSample ->
        targetControlOutcome unit = controlCellValue (targetScore unit))
    (hscoreMeasControl :
      ∀ unit, unit ∈ controlSample ->
        controlOutcome unit = controlCellValue (controlScore unit)) :
    weightedSampleMeanContrast targetSample targetWeight
        treatedTargetOutcome targetControlOutcome =
      pattWeightedMeanContrast targetSample controlSample targetWeight
        controlWeight treatedTargetOutcome controlOutcome := by
  have hcontrol :
      weightedSampleMean targetSample targetWeight targetControlOutcome =
        weightedSampleMean controlSample controlWeight controlOutcome :=
    weightedSampleMean_eq_of_scoreCellShare_eq_and_scoreMeasurable
      targetSample controlSample cells targetWeight controlWeight
      targetControlOutcome controlOutcome targetScore controlScore
      controlCellValue hcoverTarget hcoverControl hmassTarget hmassControl
      hshareControl hscoreMeasTargetControl hscoreMeasControl
  unfold weightedSampleMeanContrast pattWeightedMeanContrast
  rw [hcontrol]

end WDSM
end Matching
end StatInference
