import StatInference.EmpiricalProcess.Basic
import StatInference.Estimator.Basic

/-!
# Empirical averages and empirical risk notation

This module provides the finite-sample notation needed before proving
probabilistic uniform laws.  The definitions are deterministic: they turn a
sample and a loss/statistic into real-valued empirical averages and empirical
risks that downstream GC and ERM theorems can consume.
-/

namespace StatInference

open scoped BigOperators

universe u v

/-- Empirical average of a real-valued statistic over a fixed-size sample. -/
noncomputable def empiricalAverage {Observation : Type u} {n : ℕ}
    (sample : SampleAt Observation n) (statistic : Observation -> ℝ) : ℝ :=
  (∑ i : Fin n, statistic (sample i)) / (n : ℝ)

/-- Unfolding lemma for empirical averages. -/
theorem empiricalAverage_eq_sum_div {Observation : Type u} {n : ℕ}
    (sample : SampleAt Observation n) (statistic : Observation -> ℝ) :
    empiricalAverage sample statistic =
      (∑ i : Fin n, statistic (sample i)) / (n : ℝ) :=
  rfl

/-- Empirical risk induced by a candidate-indexed loss over one sample. -/
noncomputable def empiricalRiskOfLoss {Observation : Type u} {Candidate : Type v}
    {n : ℕ} (sample : SampleAt Observation n)
    (loss : Candidate -> Observation -> ℝ) (candidate : Candidate) : ℝ :=
  empiricalAverage sample (loss candidate)

/-- Unfolding lemma for empirical risk induced by a loss. -/
theorem empiricalRiskOfLoss_eq_average
    {Observation : Type u} {Candidate : Type v} {n : ℕ}
    (sample : SampleAt Observation n)
    (loss : Candidate -> Observation -> ℝ) (candidate : Candidate) :
    empiricalRiskOfLoss sample loss candidate =
      empiricalAverage sample (loss candidate) :=
  rfl

/-- `IndexedEmpiricalRisk` built from a loss on fixed-size product samples. -/
noncomputable def indexedEmpiricalRiskOfLoss
    (Observation : Type u) {Candidate : Type v}
    (loss : Candidate -> Observation -> ℝ) :
    IndexedEmpiricalRisk (fun n => SampleAt Observation n) Candidate where
  risk _n sample candidate := empiricalRiskOfLoss sample loss candidate

/-- Unfolding lemma for the indexed empirical-risk wrapper. -/
theorem indexedEmpiricalRiskOfLoss_apply
    (Observation : Type u) {Candidate : Type v}
    (loss : Candidate -> Observation -> ℝ)
    (n : ℕ) (sample : SampleAt Observation n) (candidate : Candidate) :
    (indexedEmpiricalRiskOfLoss Observation loss).risk n sample candidate =
      empiricalAverage sample (loss candidate) :=
  rfl

/-- Empirical-risk sequence generated by a deterministic sequence of samples. -/
noncomputable def empiricalRiskSequenceOfSamples
    {Observation : Type u} {Candidate : Type v}
    (samples : ∀ n, SampleAt Observation n)
    (loss : Candidate -> Observation -> ℝ) :
    ℕ -> Candidate -> ℝ :=
  fun n candidate => empiricalRiskOfLoss (samples n) loss candidate

/-- Unfolding lemma for empirical-risk sequences generated by samples. -/
theorem empiricalRiskSequenceOfSamples_apply
    {Observation : Type u} {Candidate : Type v}
    (samples : ∀ n, SampleAt Observation n)
    (loss : Candidate -> Observation -> ℝ)
    (n : ℕ) (candidate : Candidate) :
    empiricalRiskSequenceOfSamples samples loss n candidate =
      empiricalAverage (samples n) (loss candidate) :=
  rfl

/--
ERM excess-risk handoff for empirical risks constructed from a loss and a
sample sequence.  This keeps the notation layer directly usable by the P1
oracle inequality.
-/
theorem empiricalRiskSequence_excess_bound_of_uniform_deviation
    {Observation : Type u} {Candidate : Type v}
    (samples : ∀ n, SampleAt Observation n)
    (loss : Candidate -> Observation -> ℝ)
    (populationRisk : Candidate -> ℝ)
    (fhat : ℕ -> Candidate) (comparator : Candidate)
    (eps radius : ℕ -> ℝ)
    (h_uniform :
      EmpiricalDeviationSequence populationRisk
        (empiricalRiskSequenceOfSamples samples loss) radius)
    (h_erm :
      ∀ n,
        empiricalRiskSequenceOfSamples samples loss n (fhat n) ≤
          empiricalRiskSequenceOfSamples samples loss n comparator + eps n) :
    ∀ n,
      populationRisk (fhat n) - populationRisk comparator ≤
        2 * radius n + eps n :=
  oracle_excess_sequence_bound populationRisk
    (empiricalRiskSequenceOfSamples samples loss) fhat comparator eps radius
    (fun n candidate => h_uniform n candidate) h_erm

end StatInference
