import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
import Mathlib.MeasureTheory.Constructions.BorelSpace.Order

/-!
# Ball sigma-field foundation wrappers

This module records the Chapter 1.7 ball-measurability foundation used by
van der Vaart and Wellner.  The current layer is the ordinary metric-space
foundation: the sigma-field generated by positive-radius open balls agrees
with the Borel sigma-field in second-countable pseudometric spaces.
-/

namespace StatInference

open MeasureTheory TopologicalSpace

open scoped Topology

universe u v

/-- The family of all positive-radius open metric balls. -/
def VdVWOpenBallSets (S : Type u) [PseudoMetricSpace S] : Set (Set S) :=
  {U | ∃ x : S, ∃ r : ℝ, 0 < r ∧ U = Metric.ball x r}

/-- The sigma-field generated by all positive-radius open metric balls. -/
@[reducible]
def VdVWOpenBallMeasurableSpace (S : Type u) [PseudoMetricSpace S] : MeasurableSpace S :=
  MeasurableSpace.generateFrom (VdVWOpenBallSets S)

/-- The family of all positive-radius closed metric balls. -/
def VdVWClosedBallSets (S : Type u) [PseudoMetricSpace S] : Set (Set S) :=
  {U | ∃ x : S, ∃ r : ℝ, 0 < r ∧ U = Metric.closedBall x r}

/-- The sigma-field generated by all positive-radius closed metric balls. -/
@[reducible]
def VdVWClosedBallMeasurableSpace (S : Type u) [PseudoMetricSpace S] : MeasurableSpace S :=
  MeasurableSpace.generateFrom (VdVWClosedBallSets S)

/--
Positive-radius open metric balls form a topological basis.

This is the topological input for the VdV&W Chapter 1.7 ball sigma-field
foundation.
-/
theorem vdVWOpenBallSets_isTopologicalBasis
    {S : Type u} [PseudoMetricSpace S] :
    IsTopologicalBasis (VdVWOpenBallSets S) := by
  refine isTopologicalBasis_of_isOpen_of_nhds ?_ ?_
  · intro U hU
    rcases hU with ⟨x, r, _hr, rfl⟩
    exact Metric.isOpen_ball
  · intro a U haU hU
    rcases Metric.isOpen_iff.mp hU a haU with ⟨r, hr, hball⟩
    exact ⟨Metric.ball a r, ⟨a, r, hr, rfl⟩, Metric.mem_ball_self hr, hball⟩

/--
The VdV&W open-ball sigma-field equals the Borel sigma-field in a
second-countable pseudometric space.
-/
theorem vdVWBorel_eq_openBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] [SecondCountableTopology S] :
    borel S = VdVWOpenBallMeasurableSpace S := by
  exact vdVWOpenBallSets_isTopologicalBasis.borel_eq_generateFrom

/-- Each positive-radius open ball is measurable in the open-ball sigma-field. -/
theorem vdVWOpenBall_measurableSet
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (hr : 0 < r) :
    @MeasurableSet S (VdVWOpenBallMeasurableSpace S) (Metric.ball x r) := by
  exact MeasurableSpace.measurableSet_generateFrom ⟨x, r, hr, rfl⟩

/-- Each positive-radius closed ball is measurable in the closed-ball sigma-field. -/
theorem vdVWClosedBall_measurableSet
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (hr : 0 < r) :
    @MeasurableSet S (VdVWClosedBallMeasurableSpace S) (Metric.closedBall x r) := by
  exact MeasurableSpace.measurableSet_generateFrom ⟨x, r, hr, rfl⟩

/--
An open ball is the countable union of smaller rational-radius closed balls.

This is the countable bridge from closed-ball generators to open-ball
generators.
-/
theorem vdVW_ball_eq_iUnion_rat_closedBall
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} :
    Metric.ball x r =
      Set.iUnion fun q : {q : ℚ // 0 < (q : ℝ) ∧ (q : ℝ) < r} =>
        Metric.closedBall x ((q : ℚ) : ℝ) := by
  ext y
  constructor
  · intro hy
    have hdist : dist y x < r := by simpa [Metric.mem_ball] using hy
    rcases exists_rat_btwn hdist with ⟨q, hdistq, hqr⟩
    exact
      Set.mem_iUnion.mpr
        ⟨⟨q, lt_of_le_of_lt dist_nonneg hdistq, hqr⟩,
          by simpa [Metric.mem_closedBall] using hdistq.le⟩
  · intro hy
    rcases Set.mem_iUnion.mp hy with ⟨q, hq⟩
    have hle : dist y x ≤ (q : ℝ) := by
      simpa [Metric.mem_closedBall] using hq
    exact by
      have : dist y x < r := lt_of_le_of_lt hle q.property.2
      simpa [Metric.mem_ball] using this

/--
A closed ball is the countable intersection of larger rational-radius open
balls.

This is the countable bridge from open-ball generators to closed-ball
generators.
-/
theorem vdVW_closedBall_eq_iInter_rat_ball
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} :
    Metric.closedBall x r =
      Set.iInter fun q : {q : ℚ // r < (q : ℝ)} =>
        Metric.ball x ((q : ℚ) : ℝ) := by
  ext y
  constructor
  · intro hy
    have hle : dist y x ≤ r := by simpa [Metric.mem_closedBall] using hy
    exact Set.mem_iInter.mpr fun q => by
      have : dist y x < (q : ℝ) := lt_of_le_of_lt hle q.property
      simpa [Metric.mem_ball] using this
  · intro hy
    by_contra hnot
    have hrlt : r < dist y x := not_le.mp hnot
    rcases exists_rat_btwn hrlt with ⟨q, hrq, hqdist⟩
    have hq : dist y x < (q : ℝ) := by
      simpa [Metric.mem_ball] using Set.mem_iInter.mp hy ⟨q, hrq⟩
    exact (not_lt_of_ge hqdist.le) hq

/-- Positive-radius open balls are measurable in the closed-ball sigma-field. -/
theorem vdVWOpenBall_measurableSet_closedBallSigma
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (_hr : 0 < r) :
    @MeasurableSet S (VdVWClosedBallMeasurableSpace S) (Metric.ball x r) := by
  rw [vdVW_ball_eq_iUnion_rat_closedBall]
  exact MeasurableSet.iUnion fun q => vdVWClosedBall_measurableSet q.property.1

/-- Positive-radius closed balls are measurable in the open-ball sigma-field. -/
theorem vdVWClosedBall_measurableSet_openBallSigma
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (hr : 0 < r) :
    @MeasurableSet S (VdVWOpenBallMeasurableSpace S) (Metric.closedBall x r) := by
  rw [vdVW_closedBall_eq_iInter_rat_ball]
  exact MeasurableSet.iInter fun q =>
    vdVWOpenBall_measurableSet (lt_trans hr q.property)

/-- The open-ball sigma-field is contained in the closed-ball sigma-field. -/
theorem vdVWOpenBallMeasurableSpace_le_closedBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] :
    VdVWOpenBallMeasurableSpace S ≤ VdVWClosedBallMeasurableSpace S := by
  exact MeasurableSpace.generateFrom_le fun _ hU => by
    rcases hU with ⟨x, r, hr, rfl⟩
    exact vdVWOpenBall_measurableSet_closedBallSigma hr

/-- The closed-ball sigma-field is contained in the open-ball sigma-field. -/
theorem vdVWClosedBallMeasurableSpace_le_openBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] :
    VdVWClosedBallMeasurableSpace S ≤ VdVWOpenBallMeasurableSpace S := by
  exact MeasurableSpace.generateFrom_le fun _ hU => by
    rcases hU with ⟨x, r, hr, rfl⟩
    exact vdVWClosedBall_measurableSet_openBallSigma hr

/-- The open-ball and closed-ball sigma-fields agree. -/
theorem vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] :
    VdVWClosedBallMeasurableSpace S = VdVWOpenBallMeasurableSpace S :=
  le_antisymm vdVWClosedBallMeasurableSpace_le_openBallMeasurableSpace
    vdVWOpenBallMeasurableSpace_le_closedBallMeasurableSpace

/--
The VdV&W closed-ball sigma-field equals the Borel sigma-field in a
second-countable pseudometric space.
-/
theorem vdVWBorel_eq_closedBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] [SecondCountableTopology S] :
    borel S = VdVWClosedBallMeasurableSpace S := by
  calc
    borel S = VdVWOpenBallMeasurableSpace S :=
      vdVWBorel_eq_openBallMeasurableSpace
    _ = VdVWClosedBallMeasurableSpace S :=
      vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace.symm

/--
Distance to a fixed center is measurable for the VdV&W open-ball sigma-field.

This avoids assuming the domain is already Borel-measurable; it is the forward
direction needed for the Chapter 1.7 distance-coordinate characterization.
-/
theorem vdVW_dist_measurable_openBallSigma
    {S : Type u} [PseudoMetricSpace S] (s : S) :
    @Measurable S ℝ (VdVWOpenBallMeasurableSpace S) (borel ℝ)
      (fun x => dist x s) := by
  letI : MeasurableSpace S := VdVWOpenBallMeasurableSpace S
  change Measurable fun x : S => dist x s
  refine measurable_of_Iio ?_
  intro r
  by_cases hr : 0 < r
  · have hpre : (fun x : S => dist x s) ⁻¹' Set.Iio r = Metric.ball s r := by
      ext x
      simp [Metric.mem_ball, dist_comm]
    rw [hpre]
    exact vdVWOpenBall_measurableSet hr
  · have hrle : r ≤ 0 := le_of_not_gt hr
    have hpre : (fun x : S => dist x s) ⁻¹' Set.Iio r = (∅ : Set S) := by
      ext x
      simp [Set.mem_Iio, not_lt.mpr (le_trans hrle dist_nonneg)]
    rw [hpre]
    exact MeasurableSet.empty

/-- Bounded real transform of a metric distance. -/
noncomputable def vdVWBoundedDist {S : Type u} [PseudoMetricSpace S] (x s : S) : ℝ :=
  dist x s / (1 + dist x s)

/-- The bounded distance transform is nonnegative. -/
theorem vdVWBoundedDist_nonneg
    {S : Type u} [PseudoMetricSpace S] (x s : S) :
    0 ≤ vdVWBoundedDist x s := by
  unfold vdVWBoundedDist
  exact div_nonneg dist_nonneg (by linarith [dist_nonneg (x := x) (y := s)])

/-- The bounded distance transform is strictly below one. -/
theorem vdVWBoundedDist_lt_one
    {S : Type u} [PseudoMetricSpace S] (x s : S) :
    vdVWBoundedDist x s < 1 := by
  unfold vdVWBoundedDist
  rw [div_lt_one]
  · linarith
  · linarith [dist_nonneg (x := x) (y := s)]

/--
Strict sublevel sets of the bounded distance transform recover strict distance
sublevels.
-/
theorem vdVWBoundedDist_lt_iff_dist_lt
    {S : Type u} [PseudoMetricSpace S] {x s : S} {r : ℝ} (hr : 0 < r) :
    vdVWBoundedDist x s < r / (1 + r) ↔ dist x s < r := by
  unfold vdVWBoundedDist
  have hdpos : 0 < 1 + dist x s := by
    linarith [dist_nonneg (x := x) (y := s)]
  have hrpos : 0 < 1 + r := by linarith
  rw [div_lt_div_iff₀ hdpos hrpos]
  constructor <;> intro h <;> linarith

/--
Measurability of a distance coordinate is equivalent to measurability of its
bounded transform.
-/
theorem vdVWBoundedDist_measurable_iff_dist
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] {X : Ω → S} {s : S} :
    Measurable (fun ω => vdVWBoundedDist (X ω) s) ↔
      Measurable fun ω => dist (X ω) s := by
  constructor
  · intro hbounded
    refine measurable_of_Iio ?_
    intro r
    by_cases hr : 0 < r
    · have hpre :
          (fun ω => dist (X ω) s) ⁻¹' Set.Iio r =
            (fun ω => vdVWBoundedDist (X ω) s) ⁻¹' Set.Iio (r / (1 + r)) := by
        ext ω
        exact (vdVWBoundedDist_lt_iff_dist_lt (x := X ω) (s := s) hr).symm
      rw [hpre]
      exact hbounded measurableSet_Iio
    · have hrle : r ≤ 0 := le_of_not_gt hr
      have hpre : (fun ω => dist (X ω) s) ⁻¹' Set.Iio r = (∅ : Set Ω) := by
        ext ω
        simp [Set.mem_Iio, not_lt.mpr (le_trans hrle dist_nonneg)]
      rw [hpre]
      exact MeasurableSet.empty
  · intro hdist
    exact hdist.div (measurable_const.add hdist)

/-- Bounded distance to a fixed center is measurable for the VdV&W open-ball sigma-field. -/
theorem vdVWBoundedDist_measurable_openBallSigma
    {S : Type u} [PseudoMetricSpace S] (s : S) :
    @Measurable S ℝ (VdVWOpenBallMeasurableSpace S) (borel ℝ)
      (fun x => vdVWBoundedDist x s) := by
  letI : MeasurableSpace S := VdVWOpenBallMeasurableSpace S
  change Measurable fun x : S => vdVWBoundedDist x s
  exact (vdVWBoundedDist_measurable_iff_dist (X := fun x : S => x) (s := s)).2
    (vdVW_dist_measurable_openBallSigma s)

/-- Bounded distance to a fixed center is measurable for the VdV&W closed-ball sigma-field. -/
theorem vdVWBoundedDist_measurable_closedBallSigma
    {S : Type u} [PseudoMetricSpace S] (s : S) :
    @Measurable S ℝ (VdVWClosedBallMeasurableSpace S) (borel ℝ)
      (fun x => vdVWBoundedDist x s) := by
  rw [vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace]
  exact vdVWBoundedDist_measurable_openBallSigma s

/--
An open ball is a countable union of strict sublevel sets of distances to any
fixed dense sequence.  This is the separability step behind the VdV&W
Chapter 1.7 distance-coordinate criterion.
-/
theorem vdVW_ball_eq_iUnion_denseSeq_dist_sublevel
    {S : Type u} [PseudoMetricSpace S] {denseSeq : ℕ → S}
    (hdense : DenseRange denseSeq) (x : S) (r : ℝ) :
    Metric.ball x r =
      Set.iUnion fun n : ℕ =>
        {y : S | dist y (denseSeq n) < r - dist (denseSeq n) x} := by
  ext y
  constructor
  · intro hy
    have hyr : dist y x < r := by
      simpa [Metric.mem_ball] using hy
    have hpos : 0 < (r - dist y x) / 2 := by
      linarith
    rcases hdense.exists_dist_lt y hpos with ⟨n, hn⟩
    refine Set.mem_iUnion.mpr ⟨n, ?_⟩
    have htri : dist (denseSeq n) x ≤ dist (denseSeq n) y + dist y x :=
      dist_triangle (denseSeq n) y x
    have htri' : dist (denseSeq n) x ≤ dist y (denseSeq n) + dist y x := by
      simpa [dist_comm] using htri
    have htwice : 2 * dist y (denseSeq n) + dist y x < r := by
      linarith
    have hsum : dist y (denseSeq n) + dist (denseSeq n) x < r := by
      linarith
    show dist y (denseSeq n) < r - dist (denseSeq n) x
    linarith
  · intro hy
    rcases Set.mem_iUnion.mp hy with ⟨n, hn⟩
    have htri : dist y x ≤ dist y (denseSeq n) + dist (denseSeq n) x :=
      dist_triangle y (denseSeq n) x
    have hsub : dist y (denseSeq n) < r - dist (denseSeq n) x := hn
    have : dist y x < r := by
      linarith
    simpa [Metric.mem_ball] using this

/--
For any dense sequence, measurability into the VdV&W open-ball sigma-field is
equivalent to measurability of all distance coordinates to that sequence.
-/
theorem vdVW_measurable_openBallSigma_iff_dist_denseSeq
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] {denseSeq : ℕ → S}
    (hdense : DenseRange denseSeq) {X : Ω → S} :
    @Measurable Ω S _ (VdVWOpenBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => dist (X ω) (denseSeq n) := by
  constructor
  · intro hX n
    exact (vdVW_dist_measurable_openBallSigma (denseSeq n)).comp hX
  · intro hcoord
    refine measurable_generateFrom ?_
    intro U hU
    rcases hU with ⟨x, r, _hr, rfl⟩
    rw [vdVW_ball_eq_iUnion_denseSeq_dist_sublevel hdense x r]
    simpa [Set.preimage_iUnion] using
      (MeasurableSet.iUnion fun n => measurableSet_lt (hcoord n) measurable_const)

/--
Closed-ball measurability has the same distance-coordinate characterization,
because the open-ball and closed-ball sigma-fields agree.
-/
theorem vdVW_measurable_closedBallSigma_iff_dist_denseSeq
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] {denseSeq : ℕ → S}
    (hdense : DenseRange denseSeq) {X : Ω → S} :
    @Measurable Ω S _ (VdVWClosedBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => dist (X ω) (denseSeq n) := by
  rw [vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace]
  exact vdVW_measurable_openBallSigma_iff_dist_denseSeq hdense

/--
For any dense sequence, measurability into the VdV&W open-ball sigma-field is
equivalent to measurability of all bounded distance coordinates to that
sequence.
-/
theorem vdVW_measurable_openBallSigma_iff_boundedDist_denseSeq
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] {denseSeq : ℕ → S}
    (hdense : DenseRange denseSeq) {X : Ω → S} :
    @Measurable Ω S _ (VdVWOpenBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => vdVWBoundedDist (X ω) (denseSeq n) := by
  rw [vdVW_measurable_openBallSigma_iff_dist_denseSeq hdense]
  constructor
  · intro hcoord n
    exact (vdVWBoundedDist_measurable_iff_dist (X := X) (s := denseSeq n)).2 (hcoord n)
  · intro hcoord n
    exact (vdVWBoundedDist_measurable_iff_dist (X := X) (s := denseSeq n)).1 (hcoord n)

/--
Closed-ball measurability has the same bounded distance-coordinate
characterization, because the open-ball and closed-ball sigma-fields agree.
-/
theorem vdVW_measurable_closedBallSigma_iff_boundedDist_denseSeq
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] {denseSeq : ℕ → S}
    (hdense : DenseRange denseSeq) {X : Ω → S} :
    @Measurable Ω S _ (VdVWClosedBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => vdVWBoundedDist (X ω) (denseSeq n) := by
  rw [vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace]
  exact vdVW_measurable_openBallSigma_iff_boundedDist_denseSeq hdense

/-- Canonical dense-sequence version of the open-ball distance criterion. -/
theorem vdVWOpenBallMeasurable_iff_forall_denseSeq_dist_measurable
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] [SeparableSpace S] [Nonempty S] {X : Ω → S} :
    @Measurable Ω S _ (VdVWOpenBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => dist (X ω) (denseSeq S n) :=
  vdVW_measurable_openBallSigma_iff_dist_denseSeq (denseRange_denseSeq S)

/-- Canonical dense-sequence version of the closed-ball distance criterion. -/
theorem vdVWClosedBallMeasurable_iff_forall_denseSeq_dist_measurable
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] [SeparableSpace S] [Nonempty S] {X : Ω → S} :
    @Measurable Ω S _ (VdVWClosedBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => dist (X ω) (denseSeq S n) :=
  vdVW_measurable_closedBallSigma_iff_dist_denseSeq (denseRange_denseSeq S)

/-- Canonical dense-sequence version of the open-ball bounded distance criterion. -/
theorem vdVWOpenBallMeasurable_iff_forall_denseSeq_boundedDist_measurable
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] [SeparableSpace S] [Nonempty S] {X : Ω → S} :
    @Measurable Ω S _ (VdVWOpenBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => vdVWBoundedDist (X ω) (denseSeq S n) :=
  vdVW_measurable_openBallSigma_iff_boundedDist_denseSeq (denseRange_denseSeq S)

/-- Canonical dense-sequence version of the closed-ball bounded distance criterion. -/
theorem vdVWClosedBallMeasurable_iff_forall_denseSeq_boundedDist_measurable
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] [SeparableSpace S] [Nonempty S] {X : Ω → S} :
    @Measurable Ω S _ (VdVWClosedBallMeasurableSpace S) X ↔
      ∀ n : ℕ, Measurable fun ω => vdVWBoundedDist (X ω) (denseSeq S n) :=
  vdVW_measurable_closedBallSigma_iff_boundedDist_denseSeq (denseRange_denseSeq S)

/--
In a separable pseudometric Borel space, ordinary Borel measurability is
equivalent to measurability of all canonical dense-sequence distance
coordinates.
-/
theorem vdVWBorelMeasurable_iff_forall_denseSeq_dist_measurable
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] [MeasurableSpace S] [BorelSpace S]
    [SeparableSpace S] [Nonempty S] {X : Ω → S} :
    Measurable X ↔
      ∀ n : ℕ, Measurable fun ω => dist (X ω) (denseSeq S n) := by
  constructor
  · intro hX n
    exact hX.dist measurable_const
  · intro hcoord
    have hopen : @Measurable Ω S _ (VdVWOpenBallMeasurableSpace S) X :=
      (vdVWOpenBallMeasurable_iff_forall_denseSeq_dist_measurable (X := X)).2 hcoord
    have hEq : (inferInstance : MeasurableSpace S) = VdVWOpenBallMeasurableSpace S := by
      calc
        (inferInstance : MeasurableSpace S) = borel S := BorelSpace.measurable_eq
        _ = VdVWOpenBallMeasurableSpace S :=
          vdVWBorel_eq_openBallMeasurableSpace (S := S)
    change @Measurable Ω S _ (inferInstance : MeasurableSpace S) X
    rw [hEq]
    exact hopen

/--
In a separable pseudometric Borel space, ordinary Borel measurability is
equivalent to measurability of all canonical bounded dense-sequence distance
coordinates.
-/
theorem vdVWBorelMeasurable_iff_forall_denseSeq_boundedDist_measurable
    {Ω : Type v} [MeasurableSpace Ω]
    {S : Type u} [PseudoMetricSpace S] [MeasurableSpace S] [BorelSpace S]
    [SeparableSpace S] [Nonempty S] {X : Ω → S} :
    Measurable X ↔
      ∀ n : ℕ, Measurable fun ω => vdVWBoundedDist (X ω) (denseSeq S n) := by
  rw [vdVWBorelMeasurable_iff_forall_denseSeq_dist_measurable]
  constructor
  · intro hcoord n
    exact (vdVWBoundedDist_measurable_iff_dist (X := X) (s := denseSeq S n)).2 (hcoord n)
  · intro hcoord n
    exact (vdVWBoundedDist_measurable_iff_dist (X := X) (s := denseSeq S n)).1 (hcoord n)

end StatInference
