import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric

/-!
# Ball sigma-field foundation wrappers

This module records the Chapter 1.7 ball-measurability foundation used by
van der Vaart and Wellner.  The current layer is the ordinary metric-space
foundation: the sigma-field generated by positive-radius open balls agrees
with the Borel sigma-field in second-countable pseudometric spaces.
-/

namespace StatInference

open MeasureTheory TopologicalSpace

open scoped Topology

universe u

/-- The family of all positive-radius open metric balls. -/
def VdVWOpenBallSets (S : Type u) [PseudoMetricSpace S] : Set (Set S) :=
  {U | ∃ x : S, ∃ r : ℝ, 0 < r ∧ U = Metric.ball x r}

/-- The sigma-field generated by all positive-radius open metric balls. -/
@[reducible]
def VdVWOpenBallMeasurableSpace (S : Type u) [PseudoMetricSpace S] : MeasurableSpace S :=
  MeasurableSpace.generateFrom (VdVWOpenBallSets S)

/-- The family of all positive-radius closed metric balls. -/
def VdVWClosedBallSets (S : Type u) [PseudoMetricSpace S] : Set (Set S) :=
  {U | ∃ x : S, ∃ r : ℝ, 0 < r ∧ U = Metric.closedBall x r}

/-- The sigma-field generated by all positive-radius closed metric balls. -/
@[reducible]
def VdVWClosedBallMeasurableSpace (S : Type u) [PseudoMetricSpace S] : MeasurableSpace S :=
  MeasurableSpace.generateFrom (VdVWClosedBallSets S)

/--
Positive-radius open metric balls form a topological basis.

This is the topological input for the VdV&W Chapter 1.7 ball sigma-field
foundation.
-/
theorem vdVWOpenBallSets_isTopologicalBasis
    {S : Type u} [PseudoMetricSpace S] :
    IsTopologicalBasis (VdVWOpenBallSets S) := by
  refine isTopologicalBasis_of_isOpen_of_nhds ?_ ?_
  · intro U hU
    rcases hU with ⟨x, r, _hr, rfl⟩
    exact Metric.isOpen_ball
  · intro a U haU hU
    rcases Metric.isOpen_iff.mp hU a haU with ⟨r, hr, hball⟩
    exact ⟨Metric.ball a r, ⟨a, r, hr, rfl⟩, Metric.mem_ball_self hr, hball⟩

/--
The VdV&W open-ball sigma-field equals the Borel sigma-field in a
second-countable pseudometric space.
-/
theorem vdVWBorel_eq_openBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] [SecondCountableTopology S] :
    borel S = VdVWOpenBallMeasurableSpace S := by
  exact vdVWOpenBallSets_isTopologicalBasis.borel_eq_generateFrom

/-- Each positive-radius open ball is measurable in the open-ball sigma-field. -/
theorem vdVWOpenBall_measurableSet
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (hr : 0 < r) :
    @MeasurableSet S (VdVWOpenBallMeasurableSpace S) (Metric.ball x r) := by
  exact MeasurableSpace.measurableSet_generateFrom ⟨x, r, hr, rfl⟩

/-- Each positive-radius closed ball is measurable in the closed-ball sigma-field. -/
theorem vdVWClosedBall_measurableSet
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (hr : 0 < r) :
    @MeasurableSet S (VdVWClosedBallMeasurableSpace S) (Metric.closedBall x r) := by
  exact MeasurableSpace.measurableSet_generateFrom ⟨x, r, hr, rfl⟩

/--
An open ball is the countable union of smaller rational-radius closed balls.

This is the countable bridge from closed-ball generators to open-ball
generators.
-/
theorem vdVW_ball_eq_iUnion_rat_closedBall
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} :
    Metric.ball x r =
      Set.iUnion fun q : {q : ℚ // 0 < (q : ℝ) ∧ (q : ℝ) < r} =>
        Metric.closedBall x ((q : ℚ) : ℝ) := by
  ext y
  constructor
  · intro hy
    have hdist : dist y x < r := by simpa [Metric.mem_ball] using hy
    rcases exists_rat_btwn hdist with ⟨q, hdistq, hqr⟩
    exact
      Set.mem_iUnion.mpr
        ⟨⟨q, lt_of_le_of_lt dist_nonneg hdistq, hqr⟩,
          by simpa [Metric.mem_closedBall] using hdistq.le⟩
  · intro hy
    rcases Set.mem_iUnion.mp hy with ⟨q, hq⟩
    have hle : dist y x ≤ (q : ℝ) := by
      simpa [Metric.mem_closedBall] using hq
    exact by
      have : dist y x < r := lt_of_le_of_lt hle q.property.2
      simpa [Metric.mem_ball] using this

/--
A closed ball is the countable intersection of larger rational-radius open
balls.

This is the countable bridge from open-ball generators to closed-ball
generators.
-/
theorem vdVW_closedBall_eq_iInter_rat_ball
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} :
    Metric.closedBall x r =
      Set.iInter fun q : {q : ℚ // r < (q : ℝ)} =>
        Metric.ball x ((q : ℚ) : ℝ) := by
  ext y
  constructor
  · intro hy
    have hle : dist y x ≤ r := by simpa [Metric.mem_closedBall] using hy
    exact Set.mem_iInter.mpr fun q => by
      have : dist y x < (q : ℝ) := lt_of_le_of_lt hle q.property
      simpa [Metric.mem_ball] using this
  · intro hy
    by_contra hnot
    have hrlt : r < dist y x := not_le.mp hnot
    rcases exists_rat_btwn hrlt with ⟨q, hrq, hqdist⟩
    have hq : dist y x < (q : ℝ) := by
      simpa [Metric.mem_ball] using Set.mem_iInter.mp hy ⟨q, hrq⟩
    exact (not_lt_of_ge hqdist.le) hq

/-- Positive-radius open balls are measurable in the closed-ball sigma-field. -/
theorem vdVWOpenBall_measurableSet_closedBallSigma
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (_hr : 0 < r) :
    @MeasurableSet S (VdVWClosedBallMeasurableSpace S) (Metric.ball x r) := by
  rw [vdVW_ball_eq_iUnion_rat_closedBall]
  exact MeasurableSet.iUnion fun q => vdVWClosedBall_measurableSet q.property.1

/-- Positive-radius closed balls are measurable in the open-ball sigma-field. -/
theorem vdVWClosedBall_measurableSet_openBallSigma
    {S : Type u} [PseudoMetricSpace S] {x : S} {r : ℝ} (hr : 0 < r) :
    @MeasurableSet S (VdVWOpenBallMeasurableSpace S) (Metric.closedBall x r) := by
  rw [vdVW_closedBall_eq_iInter_rat_ball]
  exact MeasurableSet.iInter fun q =>
    vdVWOpenBall_measurableSet (lt_trans hr q.property)

/-- The open-ball sigma-field is contained in the closed-ball sigma-field. -/
theorem vdVWOpenBallMeasurableSpace_le_closedBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] :
    VdVWOpenBallMeasurableSpace S ≤ VdVWClosedBallMeasurableSpace S := by
  exact MeasurableSpace.generateFrom_le fun _ hU => by
    rcases hU with ⟨x, r, hr, rfl⟩
    exact vdVWOpenBall_measurableSet_closedBallSigma hr

/-- The closed-ball sigma-field is contained in the open-ball sigma-field. -/
theorem vdVWClosedBallMeasurableSpace_le_openBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] :
    VdVWClosedBallMeasurableSpace S ≤ VdVWOpenBallMeasurableSpace S := by
  exact MeasurableSpace.generateFrom_le fun _ hU => by
    rcases hU with ⟨x, r, hr, rfl⟩
    exact vdVWClosedBall_measurableSet_openBallSigma hr

/-- The open-ball and closed-ball sigma-fields agree. -/
theorem vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] :
    VdVWClosedBallMeasurableSpace S = VdVWOpenBallMeasurableSpace S :=
  le_antisymm vdVWClosedBallMeasurableSpace_le_openBallMeasurableSpace
    vdVWOpenBallMeasurableSpace_le_closedBallMeasurableSpace

/--
The VdV&W closed-ball sigma-field equals the Borel sigma-field in a
second-countable pseudometric space.
-/
theorem vdVWBorel_eq_closedBallMeasurableSpace
    {S : Type u} [PseudoMetricSpace S] [SecondCountableTopology S] :
    borel S = VdVWClosedBallMeasurableSpace S := by
  calc
    borel S = VdVWOpenBallMeasurableSpace S :=
      vdVWBorel_eq_openBallMeasurableSpace
    _ = VdVWClosedBallMeasurableSpace S :=
      vdVWClosedBallMeasurableSpace_eq_openBallMeasurableSpace.symm

end StatInference
